import { MigrationInterface, QueryRunner } from "typeorm";

export class CanonicalSqliteBaseline1784649333877 implements MigrationInterface {
    name = 'CanonicalSqliteBaseline1784649333877'

    public async up(queryRunner: QueryRunner): Promise<void> {
        if (queryRunner.connection.options.type !== 'sqljs') return;
        await queryRunner.query(`CREATE TABLE "mcp_servers" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "version" varchar(100) NOT NULL DEFAULT ('1.0.0'), "description" text, "port" integer NOT NULL DEFAULT (9022), "transport" varchar CHECK( "transport" IN ('streamable','sse') ) NOT NULL DEFAULT ('streamable'), "status" varchar CHECK( "status" IN ('stopped','starting','running','stopping','error') ) NOT NULL DEFAULT ('stopped'), "endpoint" text, "openApiData" text NOT NULL, "tools" text, "toolsCount" integer NOT NULL DEFAULT (0), "config" text, "authConfig" text, "lastHealthCheck" datetime, "healthy" boolean NOT NULL DEFAULT (1), "errorMessage" text, "metrics" text, "autoStart" boolean NOT NULL DEFAULT (1), "tags" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_2ee0138f3dd9575eedd37f2405f" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7ed02efd17d98567e515642eb0" ON "mcp_servers" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2ee0138f3dd9575eedd37f2405" ON "mcp_servers" ("name") `);
        await queryRunner.query(`CREATE TABLE "auth_configs" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "description" text, "type" varchar CHECK( "type" IN ('none','bearer','apikey','basic','oauth2') ) NOT NULL DEFAULT ('none'), "config" text NOT NULL, "enabled" boolean NOT NULL DEFAULT (1), "expiresAt" datetime, "lastUsed" datetime, "serverId" varchar(36) NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a9f26e310a0af26792c8762d3b" ON "auth_configs" ("serverId", "name") `);
        await queryRunner.query(`CREATE TABLE "log_entries" ("id" varchar PRIMARY KEY NOT NULL, "level" varchar CHECK( "level" IN ('debug','info','warn','error','fatal') ) NOT NULL DEFAULT ('info'), "source" varchar CHECK( "source" IN ('system','mcp_server','api','tool_execution','auth','database','health_check') ) NOT NULL DEFAULT ('system'), "message" text NOT NULL, "context" text, "metadata" text, "serverId" varchar(36), "component" varchar(100), "operation" varchar(100), "stackTrace" text, "tags" text, "timestamp" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_51bcf6d9189a9caa2956f7384d" ON "log_entries" ("level", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_88410904513ed6cfdd598a777b" ON "log_entries" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd0b54acd354a14abe257494e8" ON "log_entries" ("serverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e01fae4223e72fdd0bba2e6f6a" ON "log_entries" ("source") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1544ddc5ab67b1c768ed74a5c" ON "log_entries" ("level") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "description" varchar(255), "category" varchar CHECK( "category" IN ('system','user_management','server_management','api_management','monitoring','configuration','security','audit') ) NOT NULL, "action" varchar CHECK( "action" IN ('create','read','update','delete','execute','manage','view','export','import') ) NOT NULL, "resource" varchar(100), "enabled" boolean NOT NULL DEFAULT (1), "isSystem" boolean NOT NULL DEFAULT (0), "conditions" text, "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6cf44c88049465f900899da21e" ON "permissions" ("category", "action") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_48ce552495d14eae9b187bb671" ON "permissions" ("name") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "description" varchar(255), "type" varchar CHECK( "type" IN ('system','admin','user','custom') ) NOT NULL DEFAULT ('custom'), "enabled" boolean NOT NULL DEFAULT (1), "isDefault" boolean NOT NULL DEFAULT (0), "priority" integer NOT NULL DEFAULT (0), "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" varchar PRIMARY KEY NOT NULL, "action" varchar CHECK( "action" IN ('user_login','user_logout','user_login_failed','user_created','user_updated','user_deleted','user_password_changed','user_role_assigned','user_role_removed','user_locked','user_unlocked','server_created','server_updated','server_deleted','server_started','server_stopped','server_restarted','api_called','api_configured','api_tested','config_updated','config_exported','config_imported','config_reset','permission_granted','permission_revoked','role_created','role_updated','role_deleted','api_key_created','api_key_deleted','api_key_used','system_backup','system_restore','system_maintenance') ) NOT NULL, "description" varchar(255), "level" varchar CHECK( "level" IN ('info','warning','error','critical') ) NOT NULL DEFAULT ('info'), "status" varchar CHECK( "status" IN ('success','failed','pending') ) NOT NULL DEFAULT ('success'), "resource" varchar(100), "resourceId" varchar(255), "ipAddress" varchar(45), "userAgent" varchar(500), "sessionId" varchar(255), "details" text, "metadata" text, "userId" varchar(36), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_8ddc86298ac7fadad468b28d83" ON "audit_logs" ("ipAddress") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2961862b2704794af56359ff0a" ON "audit_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_76566a7a3b90863650d467bff6" ON "audit_logs" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "username" varchar(100) NOT NULL, "email" varchar(255) NOT NULL, "password" varchar(255) NOT NULL, "firstName" varchar(100), "lastName" varchar(100), "status" varchar CHECK( "status" IN ('active','inactive','suspended','pending') ) NOT NULL DEFAULT ('pending'), "emailVerified" boolean NOT NULL DEFAULT (0), "emailVerificationToken" varchar(255), "passwordResetToken" varchar(255), "passwordResetExpires" datetime, "lastLoginAt" datetime, "lastLoginIp" varchar(45), "loginAttempts" integer NOT NULL DEFAULT (0), "lockedUntil" datetime, "preferences" text, "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar(500) NOT NULL, "userId" varchar(36) NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "deviceInfo" varchar(255), "ipAddress" varchar(45), "userAgent" varchar(500), "lastUsedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_4542dd2f38a61354a040ba9fd57" UNIQUE ("token"))`);
        await queryRunner.query(`CREATE INDEX "IDX_56b91d98f71e3d1b649ed6e9f3" ON "refresh_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4542dd2f38a61354a040ba9fd5" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE TABLE "system_logs" ("id" varchar PRIMARY KEY NOT NULL, "eventType" varchar CHECK( "eventType" IN ('server_started','server_stopped','server_restarted','server_crashed','server_timeout','server_created','server_updated','server_deleted','server_config_changed','connection_established','connection_lost','connection_retry','connection_failed','health_check_passed','health_check_failed','system_startup','system_shutdown','system_error') ) NOT NULL, "message" varchar(500), "description" text, "level" varchar CHECK( "level" IN ('debug','info','warning','error','critical') ) NOT NULL DEFAULT ('info'), "status" varchar CHECK( "status" IN ('success','failed','in_progress','cancelled') ) NOT NULL DEFAULT ('success'), "serverId" varchar(36), "serverName" varchar(255), "serverVersion" varchar(100), "serverPort" integer, "userId" varchar(36), "source" varchar(255), "context" text, "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_f4f5248b93c3ca62ed3761b30f" ON "system_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8255879e189354927b5cd3186b" ON "system_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6fb7db174ca4aa4d0033ab62b" ON "system_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4d57d243d15a45c981aaab0e2" ON "system_logs" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa05ada70e2c999cde45172c90" ON "system_logs" ("eventType") `);
        await queryRunner.query(`CREATE INDEX "IDX_af8bc5ddf6bb239c2b40173a78" ON "system_logs" ("serverId") `);
        await queryRunner.query(`CREATE TABLE "openapi_documents" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "description" text, "content" text NOT NULL, "status" varchar CHECK( "status" IN ('draft','published','archived','valid','invalid','pending') ) NOT NULL DEFAULT ('draft'), "version" varchar(50) NOT NULL DEFAULT ('1.0.0'), "tags" text, "metadata" text, "user_id" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_54a9714fc03cfc002e301b51f0" ON "openapi_documents" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d6a5bfe2bd723f1dc5752bacf" ON "openapi_documents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a1c8bcd8eb7820826c7073421" ON "openapi_documents" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "source_service_assets" ("id" varchar PRIMARY KEY NOT NULL, "sourceKey" varchar(255) NOT NULL, "displayName" varchar(255), "description" text, "owner" varchar(255), "tags" text, "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_003e5cc6b79472ad6baaa33162" ON "source_service_assets" ("sourceKey") `);
        await queryRunner.query(`CREATE TABLE "endpoint_definitions" ("id" varchar PRIMARY KEY NOT NULL, "sourceServiceAssetId" varchar(36) NOT NULL, "method" varchar(16) NOT NULL, "path" varchar(1024) NOT NULL, "operationId" varchar(255), "summary" varchar(255), "description" text, "status" varchar CHECK( "status" IN ('draft','verified','published','degraded','offline','retired') ) NOT NULL DEFAULT ('draft'), "publishEnabled" boolean NOT NULL DEFAULT (0), "rawOperation" text, "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_795989a35d91fe69aedeaa01a3" ON "endpoint_definitions" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ebe74ec16bc2db7f76a4c662bf" ON "endpoint_definitions" ("sourceServiceAssetId", "method", "path") `);
        await queryRunner.query(`CREATE TABLE "runtime_assets" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "type" varchar CHECK( "type" IN ('mcp_server','gateway_service') ) NOT NULL, "status" varchar CHECK( "status" IN ('draft','active','degraded','offline') ) NOT NULL DEFAULT ('draft'), "displayName" varchar(255), "description" text, "policyBindingRef" varchar(100), "servicePrefix" varchar(120), "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_a1892cfa29a4fdf4ee960c1a4bc" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE INDEX "IDX_91af03862e2573dcde1f9dc54f" ON "runtime_assets" ("type", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a1892cfa29a4fdf4ee960c1a4b" ON "runtime_assets" ("name") `);
        await queryRunner.query(`CREATE TABLE "runtime_asset_endpoint_bindings" ("id" varchar PRIMARY KEY NOT NULL, "runtimeAssetId" varchar(36) NOT NULL, "endpointDefinitionId" varchar(36) NOT NULL, "status" varchar CHECK( "status" IN ('draft','active','offline') ) NOT NULL DEFAULT ('draft'), "publicationRevision" integer NOT NULL DEFAULT (0), "enabled" boolean NOT NULL DEFAULT (1), "bindingConfig" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_4e712a424ce528e5c8116ca50f" ON "runtime_asset_endpoint_bindings" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_efb699533b2cc4e467a6c428cf" ON "runtime_asset_endpoint_bindings" ("runtimeAssetId", "endpointDefinitionId") `);
        await queryRunner.query(`CREATE TABLE "publication_profiles" ("id" varchar PRIMARY KEY NOT NULL, "endpointDefinitionId" varchar(36) NOT NULL, "runtimeAssetEndpointBindingId" varchar(36), "version" integer NOT NULL DEFAULT (1), "intentName" varchar(255), "descriptionForLlm" text, "operatorNotes" text, "inputAliases" text, "constraints" text, "examples" text, "visibility" varchar(32) NOT NULL DEFAULT ('internal'), "status" varchar CHECK( "status" IN ('draft','reviewed','published','offline') ) NOT NULL DEFAULT ('draft'), "draftSource" varchar(32), "createdBy" varchar(36), "updatedBy" varchar(36), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_0bcb384804888966597b29e249" ON "publication_profiles" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f6f63d557a6caa1ff1bb69e464" ON "publication_profiles" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3f1d3709f4e13fdd17fb4524be" ON "publication_profiles" ("runtimeAssetEndpointBindingId", "version") `);
        await queryRunner.query(`CREATE INDEX "IDX_48c1bcc4789a93a9b03d7f8a10" ON "publication_profiles" ("endpointDefinitionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_700ab179bf73420e265595a3a6" ON "publication_profiles" ("endpointDefinitionId", "version") `);
        await queryRunner.query(`CREATE TABLE "publication_profile_history" ("id" varchar PRIMARY KEY NOT NULL, "endpointDefinitionId" varchar(36) NOT NULL, "runtimeAssetEndpointBindingId" varchar(36), "publicationProfileId" varchar(36) NOT NULL, "version" integer NOT NULL, "snapshot" text NOT NULL, "action" varchar(64) NOT NULL, "actorId" varchar(36), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_6be2440698e2376a5f2e84c249" ON "publication_profile_history" ("publicationProfileId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b731eef4efcd5f4013ae908082" ON "publication_profile_history" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_53f90e5c9c8544c0a427c1dcfe" ON "publication_profile_history" ("endpointDefinitionId") `);
        await queryRunner.query(`CREATE TABLE "publication_batch_runs" ("id" varchar PRIMARY KEY NOT NULL, "action" varchar CHECK( "action" IN ('publish','offline') ) NOT NULL, "status" varchar CHECK( "status" IN ('pending','success','partial','failed') ) NOT NULL DEFAULT ('pending'), "runtimeAssetId" varchar(36), "runtimeAssetType" varchar(32), "totalCount" integer NOT NULL DEFAULT (0), "successCount" integer NOT NULL DEFAULT (0), "failedCount" integer NOT NULL DEFAULT (0), "operatorId" varchar(36), "triggerSource" varchar(32) NOT NULL DEFAULT ('publication-ui'), "requestPayload" text, "resultSummary" text, "startedAt" datetime NOT NULL, "finishedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_d380c8ad525ed6964b0cd3872a" ON "publication_batch_runs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_71184961a966965f2d1a07ab08" ON "publication_batch_runs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e2e4a7e91c2e069847b69c2ba" ON "publication_batch_runs" ("operatorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_229bf64062d89f697420effc81" ON "publication_batch_runs" ("runtimeAssetId") `);
        await queryRunner.query(`CREATE TABLE "publication_audit_events" ("id" varchar PRIMARY KEY NOT NULL, "action" varchar CHECK( "action" IN ('runtime_asset.created','memberships.added','profile.updated','gateway_route.updated','membership.published','membership.offlined','batch.publish','batch.offline') ) NOT NULL, "status" varchar CHECK( "status" IN ('success','partial','failed','info') ) NOT NULL DEFAULT ('info'), "summary" varchar(255) NOT NULL, "details" text, "publicationBatchRunId" varchar(36), "runtimeAssetId" varchar(36), "runtimeAssetEndpointBindingId" varchar(36), "endpointDefinitionId" varchar(36), "sourceServiceAssetId" varchar(36), "operatorId" varchar(36), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_2d1925c76e38c461873d8f078d" ON "publication_audit_events" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_e799fc3632f5bde1659207f6b5" ON "publication_audit_events" ("operatorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_93c4ebca8d35af690a10753064" ON "publication_audit_events" ("endpointDefinitionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_978a210f3599c1c7423182f779" ON "publication_audit_events" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f8bbcb256a405eab0007a5a5b" ON "publication_audit_events" ("runtimeAssetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f9021e17e279724424f99986fd" ON "publication_audit_events" ("publicationBatchRunId") `);
        await queryRunner.query(`CREATE TABLE "endpoint_publish_bindings" ("id" varchar PRIMARY KEY NOT NULL, "endpointDefinitionId" varchar(36) NOT NULL, "runtimeAssetEndpointBindingId" varchar(36), "publicationProfileId" varchar(36), "publicationRevision" integer NOT NULL DEFAULT (0), "reviewStatus" varchar CHECK( "reviewStatus" IN ('pending','reviewed','rejected') ) NOT NULL DEFAULT ('pending'), "publishStatus" varchar CHECK( "publishStatus" IN ('draft','active','offline') ) NOT NULL DEFAULT ('draft'), "publishedToMcp" boolean NOT NULL DEFAULT (0), "publishedToHttp" boolean NOT NULL DEFAULT (0), "publishedAt" datetime, "publishedBy" varchar(36), "offlineAt" datetime, "offlineBy" varchar(36), "lastSnapshotId" varchar(36), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_a14db7f1483330b431c99b27e8" ON "endpoint_publish_bindings" ("publishStatus") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7a27af3b2b163918115580578f" ON "endpoint_publish_bindings" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf37d3b26bafade0d4d6385bc4" ON "endpoint_publish_bindings" ("endpointDefinitionId") `);
        await queryRunner.query(`CREATE TABLE "gateway_route_bindings" ("id" varchar PRIMARY KEY NOT NULL, "endpointDefinitionId" varchar(36) NOT NULL, "runtimeAssetEndpointBindingId" varchar(36), "publishBindingId" varchar(36), "routePath" varchar(255) NOT NULL, "matchHost" varchar(255), "pathMatchMode" varchar CHECK( "pathMatchMode" IN ('exact','prefix','parameter') ) NOT NULL DEFAULT ('exact'), "priority" integer NOT NULL DEFAULT (0), "upstreamPath" varchar(255) NOT NULL, "routeMethod" varchar(16) NOT NULL, "upstreamMethod" varchar(16) NOT NULL, "routeVisibility" varchar(32) NOT NULL DEFAULT ('internal'), "authPolicyRef" varchar(100), "trafficPolicyRef" varchar(100), "loggingPolicyRef" varchar(100), "cachePolicyRef" varchar(100), "rateLimitPolicyRef" varchar(100), "circuitBreakerPolicyRef" varchar(100), "timeoutMs" integer, "retryPolicy" text, "upstreamConfig" text, "routeStatusReason" text, "status" varchar CHECK( "status" IN ('draft','active','offline') ) NOT NULL DEFAULT ('draft'), "lastPublishedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_f2b83bb98b3a6ecf8fcb01c724" ON "gateway_route_bindings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_88d90bbe4eb5113863828bd2d1" ON "gateway_route_bindings" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_85c75b677c5c10bc99022797ef" ON "gateway_route_bindings" ("endpointDefinitionId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6d7b04e03e153afceed995acc4" ON "gateway_route_bindings" ("matchHost", "routePath", "routeMethod") `);
        await queryRunner.query(`CREATE TABLE "gateway_route_snapshots" ("id" varchar PRIMARY KEY NOT NULL, "runtimeAssetId" varchar(36) NOT NULL, "revision" varchar(64) NOT NULL, "fingerprint" varchar(64) NOT NULL, "routeCount" integer NOT NULL DEFAULT (0), "payload" text NOT NULL, "activatedAt" datetime NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_6e0221c655506d503484cf52e8" ON "gateway_route_snapshots" ("runtimeAssetId", "activatedAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a61ea3be16d7b504d37ea68a41" ON "gateway_route_snapshots" ("runtimeAssetId", "revision") `);
        await queryRunner.query(`CREATE TABLE "gateway_access_logs" ("id" varchar PRIMARY KEY NOT NULL, "requestId" varchar(120) NOT NULL, "correlationId" varchar(120), "runtimeAssetId" varchar(36), "runtimeMembershipId" varchar(36), "routeBindingId" varchar(36), "endpointDefinitionId" varchar(36), "method" varchar(16) NOT NULL, "routePath" varchar(255) NOT NULL, "upstreamUrl" text, "statusCode" integer, "latencyMs" integer, "clientIp" varchar(45), "actorId" varchar(36), "authMode" varchar(32), "consumerId" varchar(36), "credentialKeyId" varchar(120), "requestContentType" varchar(255), "responseContentType" varchar(255), "requestBytes" bigint, "responseBytes" bigint, "requestHeaders" text, "responseHeaders" text, "requestQuery" text, "requestBodyPreview" text, "responseBodyPreview" text, "requestBodyHash" varchar(128), "responseBodyHash" varchar(128), "captureMode" varchar(32) NOT NULL DEFAULT ('meta_only'), "errorMessage" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_1abedaf643842a1ebeff5e93ac" ON "gateway_access_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_eaf52dad83edc21428b3fa1b32" ON "gateway_access_logs" ("statusCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_f787ee33e930a71a010e53c654" ON "gateway_access_logs" ("routeBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_72f0530d4cdcc947e2e33406d1" ON "gateway_access_logs" ("runtimeMembershipId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a339d1242fc2d87f80f5b352c" ON "gateway_access_logs" ("runtimeAssetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3a4c2124d3a09a1830f500dab" ON "gateway_access_logs" ("requestId") `);
        await queryRunner.query(`CREATE TABLE "gateway_consumer_credentials" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(120) NOT NULL, "keyId" varchar(120) NOT NULL, "secretHash" varchar(128) NOT NULL, "label" varchar(255), "status" varchar CHECK( "status" IN ('active','inactive','revoked') ) NOT NULL DEFAULT ('active'), "runtimeAssetId" varchar(36), "routeBindingId" varchar(36), "metadata" text, "lastUsedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_c442960f31c4b3043466f8da08b" UNIQUE ("keyId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0e8340ccffe02d565eed3a4364" ON "gateway_consumer_credentials" ("routeBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1be17115c8ddd7233657265e8" ON "gateway_consumer_credentials" ("runtimeAssetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c54532f858d1c223d40a6d821f" ON "gateway_consumer_credentials" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c442960f31c4b3043466f8da08" ON "gateway_consumer_credentials" ("keyId") `);
        await queryRunner.query(`CREATE TABLE "runtime_metric_series" ("id" varchar PRIMARY KEY NOT NULL, "runtimeAssetId" varchar(36), "runtimeAssetEndpointBindingId" varchar(36), "endpointDefinitionId" varchar(36), "sourceServiceAssetId" varchar(36), "metricScope" varchar CHECK( "metricScope" IN ('runtime_asset','runtime_membership','endpoint_definition','source_service_asset','system') ) NOT NULL, "metricName" varchar(120) NOT NULL, "aggregationWindow" varchar CHECK( "aggregationWindow" IN ('minute','five_minutes','hour','day') ) NOT NULL, "windowStartedAt" datetime NOT NULL, "windowEndedAt" datetime NOT NULL, "metricType" varchar CHECK( "metricType" IN ('counter','gauge','histogram','rate') ) NOT NULL DEFAULT ('counter'), "value" double precision NOT NULL DEFAULT (0), "unit" varchar(32), "sampleCount" integer NOT NULL DEFAULT (1), "dimensions" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_898a4704bf170f0b4e7bee4ee8" ON "runtime_metric_series" ("metricScope", "windowStartedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b2140172938601a458984f864" ON "runtime_metric_series" ("metricName", "windowStartedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a1e48002f71ed0d77ef861ce8" ON "runtime_metric_series" ("runtimeAssetEndpointBindingId", "windowStartedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c59ed6275e5eaa43201959d4c5" ON "runtime_metric_series" ("runtimeAssetId", "windowStartedAt") `);
        await queryRunner.query(`CREATE TABLE "runtime_observability_events" ("id" varchar PRIMARY KEY NOT NULL, "runtimeAssetId" varchar(36), "runtimeAssetEndpointBindingId" varchar(36), "endpointDefinitionId" varchar(36), "sourceServiceAssetId" varchar(36), "eventFamily" varchar CHECK( "eventFamily" IN ('runtime.lifecycle','runtime.health','runtime.policy','runtime.publication','runtime.route','runtime.request','runtime.error','runtime.control') ) NOT NULL, "eventName" varchar(120) NOT NULL, "severity" varchar CHECK( "severity" IN ('debug','info','warning','error','critical') ) NOT NULL DEFAULT ('info'), "status" varchar CHECK( "status" IN ('success','failed','partial','active','offline','degraded') ) NOT NULL DEFAULT ('success'), "occurredAt" datetime NOT NULL, "correlationId" varchar(120), "actorType" varchar CHECK( "actorType" IN ('system','user','runtime','scheduler') ) NOT NULL DEFAULT ('system'), "actorId" varchar(36), "summary" varchar(500), "details" text, "dimensions" text, "retentionClass" varchar CHECK( "retentionClass" IN ('short','standard','security','long') ) NOT NULL DEFAULT ('standard'), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_2eba4d2d1deb7439058411b5ba" ON "runtime_observability_events" ("correlationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_811dbf17e22bf3f4bc0f30e47b" ON "runtime_observability_events" ("status", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd73b7b0cf638d5b3113d9d131" ON "runtime_observability_events" ("severity", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d2bb27857d9aaafbefa3c2852" ON "runtime_observability_events" ("eventFamily", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae4b736e4d2b58d32b5095b7ca" ON "runtime_observability_events" ("runtimeAssetEndpointBindingId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e1d57f7b6a4c739aa460fed3d" ON "runtime_observability_events" ("runtimeAssetId", "occurredAt") `);
        await queryRunner.query(`CREATE TABLE "runtime_observability_states" ("id" varchar PRIMARY KEY NOT NULL, "scopeType" varchar CHECK( "scopeType" IN ('runtime_asset','runtime_membership','endpoint_definition','source_service_asset') ) NOT NULL, "runtimeAssetId" varchar(36), "runtimeAssetEndpointBindingId" varchar(36), "endpointDefinitionId" varchar(36), "sourceServiceAssetId" varchar(36), "currentStatus" varchar CHECK( "currentStatus" IN ('draft','active','degraded','offline') ) NOT NULL DEFAULT ('draft'), "healthStatus" varchar CHECK( "healthStatus" IN ('unknown','healthy','degraded','unhealthy') ) NOT NULL DEFAULT ('unknown'), "severity" varchar(16), "lastEventAt" datetime, "lastSuccessAt" datetime, "lastFailureAt" datetime, "lastErrorCode" varchar(64), "lastErrorMessage" text, "summary" varchar(500), "counters" text, "gauges" text, "dimensions" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_421c630442a8b8b7a7bc12d6e8" ON "runtime_observability_states" ("healthStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9b1ccce1eeb77c96ca75d4c48" ON "runtime_observability_states" ("currentStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ad7e7f3f31d107e86154c8530" ON "runtime_observability_states" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2635524c23c3528325712110f5" ON "runtime_observability_states" ("runtimeAssetId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_31dbfa87d727d5981ed35a515c" ON "runtime_observability_states" ("scopeType", "runtimeAssetId", "runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE TABLE "ai_assistant_templates" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "description" text, "type" varchar CHECK( "type" IN ('claude_desktop','openai_assistant','anthropic_api','custom') ) NOT NULL DEFAULT ('claude_desktop'), "category" varchar CHECK( "category" IN ('general','development','business','research','education') ) NOT NULL DEFAULT ('general'), "status" varchar CHECK( "status" IN ('active','inactive','draft') ) NOT NULL DEFAULT ('active'), "configTemplate" text NOT NULL, "defaultValues" text, "validationRules" text, "tags" text, "isPublic" boolean NOT NULL DEFAULT (1), "version" varchar NOT NULL DEFAULT ('1.0.0'), "author" varchar(100), "usageCount" integer NOT NULL DEFAULT (0), "rating" decimal(3,2) NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_671f38118641e729c0b7669958" ON "ai_assistant_templates" ("status", "isPublic") `);
        await queryRunner.query(`CREATE INDEX "IDX_808d57a7a3e56bc043eba39545" ON "ai_assistant_templates" ("type", "category") `);
        await queryRunner.query(`CREATE TABLE "ai_assistant_configs" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "description" text, "templateId" varchar(36) NOT NULL, "generatedConfig" text NOT NULL, "customParameters" text, "status" varchar CHECK( "status" IN ('generated','exported','applied','archived') ) NOT NULL DEFAULT ('generated'), "exportFormat" varchar CHECK( "exportFormat" IN ('json','yaml','env','shell_script') ), "exportedContent" text, "tags" text, "isFavorite" boolean NOT NULL DEFAULT (0), "usageCount" integer NOT NULL DEFAULT (0), "lastUsedAt" datetime, "createdBy" varchar(100), "notes" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_05e34065f9197f0075ac77f780" ON "ai_assistant_configs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d12dfdffd091b709a66048207" ON "ai_assistant_configs" ("templateId", "status") `);
        await queryRunner.query(`CREATE TABLE "source_service_instances" ("id" varchar PRIMARY KEY NOT NULL, "sourceServiceAssetId" varchar(36) NOT NULL, "name" varchar(255) NOT NULL, "environment" varchar(100) NOT NULL, "scheme" varchar(16) NOT NULL, "host" varchar(255) NOT NULL, "port" integer NOT NULL, "basePath" varchar(1024) NOT NULL DEFAULT ('/'), "enabled" boolean NOT NULL DEFAULT (1), "status" varchar CHECK( "status" IN ('draft','healthy','unhealthy','offline') ) NOT NULL DEFAULT ('draft'), "priority" integer NOT NULL DEFAULT (100), "weight" integer NOT NULL DEFAULT (100), "isDefault" boolean NOT NULL DEFAULT (0), "credentialRef" varchar(255), "tlsPolicyRef" varchar(255), "metadata" text, "lastProbeStatus" varchar(32), "lastProbeAt" datetime, "lastProbeLatencyMs" integer, "lastError" text, "archivedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_f390aaa00963aaf930b7f96f51" ON "source_service_instances" ("status", "enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd1964571f38932f02b96aebd8" ON "source_service_instances" ("sourceServiceAssetId", "environment", "enabled") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0f92e685581c791458b6c8af68" ON "source_service_instances" ("sourceServiceAssetId", "environment", "name") `);
        await queryRunner.query(`CREATE TABLE "endpoint_test_cases" ("id" varchar PRIMARY KEY NOT NULL, "endpointDefinitionId" varchar(36) NOT NULL, "name" varchar(255) NOT NULL, "description" text, "enabled" boolean NOT NULL DEFAULT (1), "requestTemplate" text, "assertions" text, "tags" text, "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_2ee693e52d2c1e4d465d532815" ON "endpoint_test_cases" ("endpointDefinitionId", "enabled") `);
        await queryRunner.query(`CREATE TABLE "endpoint_test_runs" ("id" varchar PRIMARY KEY NOT NULL, "endpointDefinitionId" varchar(36) NOT NULL, "testCaseId" varchar(36), "sourceServiceInstanceId" varchar(36), "status" varchar CHECK( "status" IN ('success','failed') ) NOT NULL, "requestHeaders" text, "requestPayload" text, "responseStatusCode" integer, "responseHeaders" text, "responsePayload" text, "durationMs" integer, "errorMessage" text, "metadata" text, "executedAt" datetime NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_33b89528103648b88c7c86bb82" ON "endpoint_test_runs" ("status", "executedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec7ed8579a9a2114ef1eb00a03" ON "endpoint_test_runs" ("testCaseId", "executedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c053461aadc401b6d584d493e3" ON "endpoint_test_runs" ("endpointDefinitionId", "executedAt") `);
        await queryRunner.query(`CREATE TABLE "endpoint_test_samples" ("id" varchar PRIMARY KEY NOT NULL, "endpointDefinitionId" varchar(36) NOT NULL, "testCaseId" varchar(36), "testRunId" varchar(36) NOT NULL, "sourceServiceInstanceId" varchar(36), "fingerprint" varchar(64) NOT NULL, "title" varchar(255), "note" text, "enabled" boolean NOT NULL DEFAULT (1), "status" varchar CHECK( "status" IN ('active','archived') ) NOT NULL DEFAULT ('active'), "requestHeaders" text, "requestPayload" text, "responseStatusCode" integer NOT NULL, "responseHeaders" text, "responsePayload" text, "durationMs" integer, "tags" text, "metadata" text, "capturedAt" datetime NOT NULL, "archivedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_8f854a950227a717bf6f726c09" ON "endpoint_test_samples" ("status", "enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_729ae6099b4bb9144f2639f819" ON "endpoint_test_samples" ("fingerprint") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1479053976c4686906b199cb3" ON "endpoint_test_samples" ("endpointDefinitionId", "capturedAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ab7fff83ce10709684bd168008" ON "endpoint_test_samples" ("testRunId") `);
        await queryRunner.query(`CREATE TABLE "runtime_upstream_bindings" ("id" varchar PRIMARY KEY NOT NULL, "runtimeAssetEndpointBindingId" varchar(36) NOT NULL, "sourceServiceAssetId" varchar(36) NOT NULL, "environment" varchar(100) NOT NULL, "selectionMode" varchar CHECK( "selectionMode" IN ('fixed_primary','healthy_priority') ) NOT NULL, "primaryInstanceId" varchar(36), "status" varchar CHECK( "status" IN ('draft','verified','active','blocked') ) NOT NULL DEFAULT ('draft'), "revision" integer NOT NULL DEFAULT (1), "lastVerifiedAt" datetime, "lastVerificationRunId" varchar(36), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_ba9afe6c99646ad9d4728e63a30" UNIQUE ("runtimeAssetEndpointBindingId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_96605e5f3fa22aebadcdc1ea44" ON "runtime_upstream_bindings" ("environment", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ba9afe6c99646ad9d4728e63a3" ON "runtime_upstream_bindings" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE TABLE "runtime_upstream_binding_instances" ("id" varchar PRIMARY KEY NOT NULL, "runtimeUpstreamBindingId" varchar(36) NOT NULL, "sourceServiceInstanceId" varchar(36) NOT NULL, "priority" integer NOT NULL DEFAULT (0), "orderIndex" integer NOT NULL DEFAULT (0), "weight" integer NOT NULL DEFAULT (1), "enabled" boolean NOT NULL DEFAULT (1), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_71d64ae3f496cedfc72e780331" ON "runtime_upstream_binding_instances" ("runtimeUpstreamBindingId", "enabled", "priority", "orderIndex") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d99880dc022aa1ee886688e887" ON "runtime_upstream_binding_instances" ("runtimeUpstreamBindingId", "sourceServiceInstanceId") `);
        await queryRunner.query(`CREATE TABLE "runtime_verification_runs" ("id" varchar PRIMARY KEY NOT NULL, "runtimeAssetId" varchar(36) NOT NULL, "candidateRevision" varchar(64) NOT NULL, "previousActiveRevision" varchar(64), "trigger" varchar CHECK( "trigger" IN ('deploy','redeploy','upstream_change','manual') ) NOT NULL, "status" varchar CHECK( "status" IN ('planned','running','passed','failed','blocked') ) NOT NULL, "activationStatus" varchar CHECK( "activationStatus" IN ('not_attempted','activated','retained_previous','blocked') ) NOT NULL DEFAULT ('not_attempted'), "totalCount" integer NOT NULL DEFAULT (0), "passedCount" integer NOT NULL DEFAULT (0), "failedCount" integer NOT NULL DEFAULT (0), "blockedCount" integer NOT NULL DEFAULT (0), "upstreamBindingRevisions" text, "blockers" text, "metadata" text, "startedAt" datetime, "completedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_f1eb19f920ad31ee40dcfa4257" ON "runtime_verification_runs" ("candidateRevision") `);
        await queryRunner.query(`CREATE INDEX "IDX_d19d1e5ac1f2ef9f95ae43199c" ON "runtime_verification_runs" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7621e2f741ca28bd3d948dca51" ON "runtime_verification_runs" ("runtimeAssetId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "runtime_verification_results" ("id" varchar PRIMARY KEY NOT NULL, "verificationRunId" varchar(36) NOT NULL, "runtimeMembershipId" varchar(36) NOT NULL, "endpointDefinitionId" varchar(36) NOT NULL, "endpointTestSampleId" varchar(36), "kind" varchar CHECK( "kind" IN ('smoke','regression','precondition','waiver') ) NOT NULL, "status" varchar CHECK( "status" IN ('pending','passed','failed','blocked','skipped') ) NOT NULL, "blockerCode" varchar(100), "errorMessage" text, "expectedStatusCode" integer, "actualStatusCode" integer, "durationMs" integer, "evidence" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE INDEX "IDX_7c0770c6fc1c6bb2d49f19bc44" ON "runtime_verification_results" ("endpointTestSampleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3f8f3f41a8bd665724bf9613d" ON "runtime_verification_results" ("verificationRunId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b94c9d86a0f5adda3d796f3e1c" ON "runtime_verification_results" ("verificationRunId", "runtimeMembershipId") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("roleId" varchar NOT NULL, "permissionId" varchar NOT NULL, PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4599f8b8f548d35850afa2d12" ON "role_permissions" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_06792d0c62ce6b0203c03643cd" ON "role_permissions" ("permissionId") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("userId" varchar NOT NULL, "roleId" varchar NOT NULL, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_472b25323af01488f1f66a06b6" ON "user_roles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_86033897c009fcca8b6505d6be" ON "user_roles" ("roleId") `);
        await queryRunner.query(`DROP INDEX "IDX_a9f26e310a0af26792c8762d3b"`);
        await queryRunner.query(`CREATE TABLE "temporary_auth_configs" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "description" text, "type" varchar CHECK( "type" IN ('none','bearer','apikey','basic','oauth2') ) NOT NULL DEFAULT ('none'), "config" text NOT NULL, "enabled" boolean NOT NULL DEFAULT (1), "expiresAt" datetime, "lastUsed" datetime, "serverId" varchar(36) NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_c26de0f660ca6967931440c41e6" FOREIGN KEY ("serverId") REFERENCES "mcp_servers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_auth_configs"("id", "name", "description", "type", "config", "enabled", "expiresAt", "lastUsed", "serverId", "createdAt", "updatedAt") SELECT "id", "name", "description", "type", "config", "enabled", "expiresAt", "lastUsed", "serverId", "createdAt", "updatedAt" FROM "auth_configs"`);
        await queryRunner.query(`DROP TABLE "auth_configs"`);
        await queryRunner.query(`ALTER TABLE "temporary_auth_configs" RENAME TO "auth_configs"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a9f26e310a0af26792c8762d3b" ON "auth_configs" ("serverId", "name") `);
        await queryRunner.query(`DROP INDEX "IDX_51bcf6d9189a9caa2956f7384d"`);
        await queryRunner.query(`DROP INDEX "IDX_88410904513ed6cfdd598a777b"`);
        await queryRunner.query(`DROP INDEX "IDX_bd0b54acd354a14abe257494e8"`);
        await queryRunner.query(`DROP INDEX "IDX_e01fae4223e72fdd0bba2e6f6a"`);
        await queryRunner.query(`DROP INDEX "IDX_c1544ddc5ab67b1c768ed74a5c"`);
        await queryRunner.query(`CREATE TABLE "temporary_log_entries" ("id" varchar PRIMARY KEY NOT NULL, "level" varchar CHECK( "level" IN ('debug','info','warn','error','fatal') ) NOT NULL DEFAULT ('info'), "source" varchar CHECK( "source" IN ('system','mcp_server','api','tool_execution','auth','database','health_check') ) NOT NULL DEFAULT ('system'), "message" text NOT NULL, "context" text, "metadata" text, "serverId" varchar(36), "component" varchar(100), "operation" varchar(100), "stackTrace" text, "tags" text, "timestamp" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_bd0b54acd354a14abe257494e82" FOREIGN KEY ("serverId") REFERENCES "mcp_servers" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_log_entries"("id", "level", "source", "message", "context", "metadata", "serverId", "component", "operation", "stackTrace", "tags", "timestamp") SELECT "id", "level", "source", "message", "context", "metadata", "serverId", "component", "operation", "stackTrace", "tags", "timestamp" FROM "log_entries"`);
        await queryRunner.query(`DROP TABLE "log_entries"`);
        await queryRunner.query(`ALTER TABLE "temporary_log_entries" RENAME TO "log_entries"`);
        await queryRunner.query(`CREATE INDEX "IDX_51bcf6d9189a9caa2956f7384d" ON "log_entries" ("level", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_88410904513ed6cfdd598a777b" ON "log_entries" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd0b54acd354a14abe257494e8" ON "log_entries" ("serverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e01fae4223e72fdd0bba2e6f6a" ON "log_entries" ("source") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1544ddc5ab67b1c768ed74a5c" ON "log_entries" ("level") `);
        await queryRunner.query(`DROP INDEX "IDX_8ddc86298ac7fadad468b28d83"`);
        await queryRunner.query(`DROP INDEX "IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "IDX_2961862b2704794af56359ff0a"`);
        await queryRunner.query(`DROP INDEX "IDX_76566a7a3b90863650d467bff6"`);
        await queryRunner.query(`DROP INDEX "IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`CREATE TABLE "temporary_audit_logs" ("id" varchar PRIMARY KEY NOT NULL, "action" varchar CHECK( "action" IN ('user_login','user_logout','user_login_failed','user_created','user_updated','user_deleted','user_password_changed','user_role_assigned','user_role_removed','user_locked','user_unlocked','server_created','server_updated','server_deleted','server_started','server_stopped','server_restarted','api_called','api_configured','api_tested','config_updated','config_exported','config_imported','config_reset','permission_granted','permission_revoked','role_created','role_updated','role_deleted','api_key_created','api_key_deleted','api_key_used','system_backup','system_restore','system_maintenance') ) NOT NULL, "description" varchar(255), "level" varchar CHECK( "level" IN ('info','warning','error','critical') ) NOT NULL DEFAULT ('info'), "status" varchar CHECK( "status" IN ('success','failed','pending') ) NOT NULL DEFAULT ('success'), "resource" varchar(100), "resourceId" varchar(255), "ipAddress" varchar(45), "userAgent" varchar(500), "sessionId" varchar(255), "details" text, "metadata" text, "userId" varchar(36), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_audit_logs"("id", "action", "description", "level", "status", "resource", "resourceId", "ipAddress", "userAgent", "sessionId", "details", "metadata", "userId", "createdAt") SELECT "id", "action", "description", "level", "status", "resource", "resourceId", "ipAddress", "userAgent", "sessionId", "details", "metadata", "userId", "createdAt" FROM "audit_logs"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`ALTER TABLE "temporary_audit_logs" RENAME TO "audit_logs"`);
        await queryRunner.query(`CREATE INDEX "IDX_8ddc86298ac7fadad468b28d83" ON "audit_logs" ("ipAddress") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2961862b2704794af56359ff0a" ON "audit_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_76566a7a3b90863650d467bff6" ON "audit_logs" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_56b91d98f71e3d1b649ed6e9f3"`);
        await queryRunner.query(`DROP INDEX "IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP INDEX "IDX_4542dd2f38a61354a040ba9fd5"`);
        await queryRunner.query(`CREATE TABLE "temporary_refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar(500) NOT NULL, "userId" varchar(36) NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "deviceInfo" varchar(255), "ipAddress" varchar(45), "userAgent" varchar(500), "lastUsedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_4542dd2f38a61354a040ba9fd57" UNIQUE ("token"), CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_refresh_tokens"("id", "token", "userId", "expiresAt", "isRevoked", "deviceInfo", "ipAddress", "userAgent", "lastUsedAt", "createdAt", "updatedAt") SELECT "id", "token", "userId", "expiresAt", "isRevoked", "deviceInfo", "ipAddress", "userAgent", "lastUsedAt", "createdAt", "updatedAt" FROM "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`ALTER TABLE "temporary_refresh_tokens" RENAME TO "refresh_tokens"`);
        await queryRunner.query(`CREATE INDEX "IDX_56b91d98f71e3d1b649ed6e9f3" ON "refresh_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4542dd2f38a61354a040ba9fd5" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`DROP INDEX "IDX_f4f5248b93c3ca62ed3761b30f"`);
        await queryRunner.query(`DROP INDEX "IDX_8255879e189354927b5cd3186b"`);
        await queryRunner.query(`DROP INDEX "IDX_c6fb7db174ca4aa4d0033ab62b"`);
        await queryRunner.query(`DROP INDEX "IDX_a4d57d243d15a45c981aaab0e2"`);
        await queryRunner.query(`DROP INDEX "IDX_aa05ada70e2c999cde45172c90"`);
        await queryRunner.query(`DROP INDEX "IDX_af8bc5ddf6bb239c2b40173a78"`);
        await queryRunner.query(`CREATE TABLE "temporary_system_logs" ("id" varchar PRIMARY KEY NOT NULL, "eventType" varchar CHECK( "eventType" IN ('server_started','server_stopped','server_restarted','server_crashed','server_timeout','server_created','server_updated','server_deleted','server_config_changed','connection_established','connection_lost','connection_retry','connection_failed','health_check_passed','health_check_failed','system_startup','system_shutdown','system_error') ) NOT NULL, "message" varchar(500), "description" text, "level" varchar CHECK( "level" IN ('debug','info','warning','error','critical') ) NOT NULL DEFAULT ('info'), "status" varchar CHECK( "status" IN ('success','failed','in_progress','cancelled') ) NOT NULL DEFAULT ('success'), "serverId" varchar(36), "serverName" varchar(255), "serverVersion" varchar(100), "serverPort" integer, "userId" varchar(36), "source" varchar(255), "context" text, "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_af8bc5ddf6bb239c2b40173a78b" FOREIGN KEY ("serverId") REFERENCES "mcp_servers" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_f4f5248b93c3ca62ed3761b30f1" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_system_logs"("id", "eventType", "message", "description", "level", "status", "serverId", "serverName", "serverVersion", "serverPort", "userId", "source", "context", "metadata", "createdAt") SELECT "id", "eventType", "message", "description", "level", "status", "serverId", "serverName", "serverVersion", "serverPort", "userId", "source", "context", "metadata", "createdAt" FROM "system_logs"`);
        await queryRunner.query(`DROP TABLE "system_logs"`);
        await queryRunner.query(`ALTER TABLE "temporary_system_logs" RENAME TO "system_logs"`);
        await queryRunner.query(`CREATE INDEX "IDX_f4f5248b93c3ca62ed3761b30f" ON "system_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8255879e189354927b5cd3186b" ON "system_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6fb7db174ca4aa4d0033ab62b" ON "system_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4d57d243d15a45c981aaab0e2" ON "system_logs" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa05ada70e2c999cde45172c90" ON "system_logs" ("eventType") `);
        await queryRunner.query(`CREATE INDEX "IDX_af8bc5ddf6bb239c2b40173a78" ON "system_logs" ("serverId") `);
        await queryRunner.query(`DROP INDEX "IDX_54a9714fc03cfc002e301b51f0"`);
        await queryRunner.query(`DROP INDEX "IDX_2d6a5bfe2bd723f1dc5752bacf"`);
        await queryRunner.query(`DROP INDEX "IDX_3a1c8bcd8eb7820826c7073421"`);
        await queryRunner.query(`CREATE TABLE "temporary_openapi_documents" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "description" text, "content" text NOT NULL, "status" varchar CHECK( "status" IN ('draft','published','archived','valid','invalid','pending') ) NOT NULL DEFAULT ('draft'), "version" varchar(50) NOT NULL DEFAULT ('1.0.0'), "tags" text, "metadata" text, "user_id" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_3a1c8bcd8eb7820826c7073421d" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_openapi_documents"("id", "name", "description", "content", "status", "version", "tags", "metadata", "user_id", "createdAt", "updatedAt") SELECT "id", "name", "description", "content", "status", "version", "tags", "metadata", "user_id", "createdAt", "updatedAt" FROM "openapi_documents"`);
        await queryRunner.query(`DROP TABLE "openapi_documents"`);
        await queryRunner.query(`ALTER TABLE "temporary_openapi_documents" RENAME TO "openapi_documents"`);
        await queryRunner.query(`CREATE INDEX "IDX_54a9714fc03cfc002e301b51f0" ON "openapi_documents" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d6a5bfe2bd723f1dc5752bacf" ON "openapi_documents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a1c8bcd8eb7820826c7073421" ON "openapi_documents" ("user_id") `);
        await queryRunner.query(`DROP INDEX "IDX_05e34065f9197f0075ac77f780"`);
        await queryRunner.query(`DROP INDEX "IDX_0d12dfdffd091b709a66048207"`);
        await queryRunner.query(`CREATE TABLE "temporary_ai_assistant_configs" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "description" text, "templateId" varchar(36) NOT NULL, "generatedConfig" text NOT NULL, "customParameters" text, "status" varchar CHECK( "status" IN ('generated','exported','applied','archived') ) NOT NULL DEFAULT ('generated'), "exportFormat" varchar CHECK( "exportFormat" IN ('json','yaml','env','shell_script') ), "exportedContent" text, "tags" text, "isFavorite" boolean NOT NULL DEFAULT (0), "usageCount" integer NOT NULL DEFAULT (0), "lastUsedAt" datetime, "createdBy" varchar(100), "notes" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_7fc97afe3f88aafbf18c408c0a2" FOREIGN KEY ("templateId") REFERENCES "ai_assistant_templates" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_ai_assistant_configs"("id", "name", "description", "templateId", "generatedConfig", "customParameters", "status", "exportFormat", "exportedContent", "tags", "isFavorite", "usageCount", "lastUsedAt", "createdBy", "notes", "createdAt", "updatedAt") SELECT "id", "name", "description", "templateId", "generatedConfig", "customParameters", "status", "exportFormat", "exportedContent", "tags", "isFavorite", "usageCount", "lastUsedAt", "createdBy", "notes", "createdAt", "updatedAt" FROM "ai_assistant_configs"`);
        await queryRunner.query(`DROP TABLE "ai_assistant_configs"`);
        await queryRunner.query(`ALTER TABLE "temporary_ai_assistant_configs" RENAME TO "ai_assistant_configs"`);
        await queryRunner.query(`CREATE INDEX "IDX_05e34065f9197f0075ac77f780" ON "ai_assistant_configs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d12dfdffd091b709a66048207" ON "ai_assistant_configs" ("templateId", "status") `);
        await queryRunner.query(`DROP INDEX "IDX_f390aaa00963aaf930b7f96f51"`);
        await queryRunner.query(`DROP INDEX "IDX_bd1964571f38932f02b96aebd8"`);
        await queryRunner.query(`DROP INDEX "IDX_0f92e685581c791458b6c8af68"`);
        await queryRunner.query(`CREATE TABLE "temporary_source_service_instances" ("id" varchar PRIMARY KEY NOT NULL, "sourceServiceAssetId" varchar(36) NOT NULL, "name" varchar(255) NOT NULL, "environment" varchar(100) NOT NULL, "scheme" varchar(16) NOT NULL, "host" varchar(255) NOT NULL, "port" integer NOT NULL, "basePath" varchar(1024) NOT NULL DEFAULT ('/'), "enabled" boolean NOT NULL DEFAULT (1), "status" varchar CHECK( "status" IN ('draft','healthy','unhealthy','offline') ) NOT NULL DEFAULT ('draft'), "priority" integer NOT NULL DEFAULT (100), "weight" integer NOT NULL DEFAULT (100), "isDefault" boolean NOT NULL DEFAULT (0), "credentialRef" varchar(255), "tlsPolicyRef" varchar(255), "metadata" text, "lastProbeStatus" varchar(32), "lastProbeAt" datetime, "lastProbeLatencyMs" integer, "lastError" text, "archivedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_48f531b0175e91696f5cd0100f9" FOREIGN KEY ("sourceServiceAssetId") REFERENCES "source_service_assets" ("id") ON DELETE CASCADE ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_source_service_instances"("id", "sourceServiceAssetId", "name", "environment", "scheme", "host", "port", "basePath", "enabled", "status", "priority", "weight", "isDefault", "credentialRef", "tlsPolicyRef", "metadata", "lastProbeStatus", "lastProbeAt", "lastProbeLatencyMs", "lastError", "archivedAt", "createdAt", "updatedAt") SELECT "id", "sourceServiceAssetId", "name", "environment", "scheme", "host", "port", "basePath", "enabled", "status", "priority", "weight", "isDefault", "credentialRef", "tlsPolicyRef", "metadata", "lastProbeStatus", "lastProbeAt", "lastProbeLatencyMs", "lastError", "archivedAt", "createdAt", "updatedAt" FROM "source_service_instances"`);
        await queryRunner.query(`DROP TABLE "source_service_instances"`);
        await queryRunner.query(`ALTER TABLE "temporary_source_service_instances" RENAME TO "source_service_instances"`);
        await queryRunner.query(`CREATE INDEX "IDX_f390aaa00963aaf930b7f96f51" ON "source_service_instances" ("status", "enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd1964571f38932f02b96aebd8" ON "source_service_instances" ("sourceServiceAssetId", "environment", "enabled") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0f92e685581c791458b6c8af68" ON "source_service_instances" ("sourceServiceAssetId", "environment", "name") `);
        await queryRunner.query(`DROP INDEX "IDX_b4599f8b8f548d35850afa2d12"`);
        await queryRunner.query(`DROP INDEX "IDX_06792d0c62ce6b0203c03643cd"`);
        await queryRunner.query(`CREATE TABLE "temporary_role_permissions" ("roleId" varchar NOT NULL, "permissionId" varchar NOT NULL, CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c" FOREIGN KEY ("roleId") REFERENCES "roles" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd" FOREIGN KEY ("permissionId") REFERENCES "permissions" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`INSERT INTO "temporary_role_permissions"("roleId", "permissionId") SELECT "roleId", "permissionId" FROM "role_permissions"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`ALTER TABLE "temporary_role_permissions" RENAME TO "role_permissions"`);
        await queryRunner.query(`CREATE INDEX "IDX_b4599f8b8f548d35850afa2d12" ON "role_permissions" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_06792d0c62ce6b0203c03643cd" ON "role_permissions" ("permissionId") `);
        await queryRunner.query(`DROP INDEX "IDX_472b25323af01488f1f66a06b6"`);
        await queryRunner.query(`DROP INDEX "IDX_86033897c009fcca8b6505d6be"`);
        await queryRunner.query(`CREATE TABLE "temporary_user_roles" ("userId" varchar NOT NULL, "roleId" varchar NOT NULL, CONSTRAINT "FK_472b25323af01488f1f66a06b67" FOREIGN KEY ("userId") REFERENCES "users" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "FK_86033897c009fcca8b6505d6be2" FOREIGN KEY ("roleId") REFERENCES "roles" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`INSERT INTO "temporary_user_roles"("userId", "roleId") SELECT "userId", "roleId" FROM "user_roles"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`ALTER TABLE "temporary_user_roles" RENAME TO "user_roles"`);
        await queryRunner.query(`CREATE INDEX "IDX_472b25323af01488f1f66a06b6" ON "user_roles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_86033897c009fcca8b6505d6be" ON "user_roles" ("roleId") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        if (queryRunner.connection.options.type !== 'sqljs') return;
        await queryRunner.query(`DROP INDEX "IDX_86033897c009fcca8b6505d6be"`);
        await queryRunner.query(`DROP INDEX "IDX_472b25323af01488f1f66a06b6"`);
        await queryRunner.query(`ALTER TABLE "user_roles" RENAME TO "temporary_user_roles"`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("userId" varchar NOT NULL, "roleId" varchar NOT NULL, PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`INSERT INTO "user_roles"("userId", "roleId") SELECT "userId", "roleId" FROM "temporary_user_roles"`);
        await queryRunner.query(`DROP TABLE "temporary_user_roles"`);
        await queryRunner.query(`CREATE INDEX "IDX_86033897c009fcca8b6505d6be" ON "user_roles" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_472b25323af01488f1f66a06b6" ON "user_roles" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_06792d0c62ce6b0203c03643cd"`);
        await queryRunner.query(`DROP INDEX "IDX_b4599f8b8f548d35850afa2d12"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" RENAME TO "temporary_role_permissions"`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("roleId" varchar NOT NULL, "permissionId" varchar NOT NULL, PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`INSERT INTO "role_permissions"("roleId", "permissionId") SELECT "roleId", "permissionId" FROM "temporary_role_permissions"`);
        await queryRunner.query(`DROP TABLE "temporary_role_permissions"`);
        await queryRunner.query(`CREATE INDEX "IDX_06792d0c62ce6b0203c03643cd" ON "role_permissions" ("permissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4599f8b8f548d35850afa2d12" ON "role_permissions" ("roleId") `);
        await queryRunner.query(`DROP INDEX "IDX_0f92e685581c791458b6c8af68"`);
        await queryRunner.query(`DROP INDEX "IDX_bd1964571f38932f02b96aebd8"`);
        await queryRunner.query(`DROP INDEX "IDX_f390aaa00963aaf930b7f96f51"`);
        await queryRunner.query(`ALTER TABLE "source_service_instances" RENAME TO "temporary_source_service_instances"`);
        await queryRunner.query(`CREATE TABLE "source_service_instances" ("id" varchar PRIMARY KEY NOT NULL, "sourceServiceAssetId" varchar(36) NOT NULL, "name" varchar(255) NOT NULL, "environment" varchar(100) NOT NULL, "scheme" varchar(16) NOT NULL, "host" varchar(255) NOT NULL, "port" integer NOT NULL, "basePath" varchar(1024) NOT NULL DEFAULT ('/'), "enabled" boolean NOT NULL DEFAULT (1), "status" varchar CHECK( "status" IN ('draft','healthy','unhealthy','offline') ) NOT NULL DEFAULT ('draft'), "priority" integer NOT NULL DEFAULT (100), "weight" integer NOT NULL DEFAULT (100), "isDefault" boolean NOT NULL DEFAULT (0), "credentialRef" varchar(255), "tlsPolicyRef" varchar(255), "metadata" text, "lastProbeStatus" varchar(32), "lastProbeAt" datetime, "lastProbeLatencyMs" integer, "lastError" text, "archivedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "source_service_instances"("id", "sourceServiceAssetId", "name", "environment", "scheme", "host", "port", "basePath", "enabled", "status", "priority", "weight", "isDefault", "credentialRef", "tlsPolicyRef", "metadata", "lastProbeStatus", "lastProbeAt", "lastProbeLatencyMs", "lastError", "archivedAt", "createdAt", "updatedAt") SELECT "id", "sourceServiceAssetId", "name", "environment", "scheme", "host", "port", "basePath", "enabled", "status", "priority", "weight", "isDefault", "credentialRef", "tlsPolicyRef", "metadata", "lastProbeStatus", "lastProbeAt", "lastProbeLatencyMs", "lastError", "archivedAt", "createdAt", "updatedAt" FROM "temporary_source_service_instances"`);
        await queryRunner.query(`DROP TABLE "temporary_source_service_instances"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0f92e685581c791458b6c8af68" ON "source_service_instances" ("sourceServiceAssetId", "environment", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd1964571f38932f02b96aebd8" ON "source_service_instances" ("sourceServiceAssetId", "environment", "enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_f390aaa00963aaf930b7f96f51" ON "source_service_instances" ("status", "enabled") `);
        await queryRunner.query(`DROP INDEX "IDX_0d12dfdffd091b709a66048207"`);
        await queryRunner.query(`DROP INDEX "IDX_05e34065f9197f0075ac77f780"`);
        await queryRunner.query(`ALTER TABLE "ai_assistant_configs" RENAME TO "temporary_ai_assistant_configs"`);
        await queryRunner.query(`CREATE TABLE "ai_assistant_configs" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(100) NOT NULL, "description" text, "templateId" varchar(36) NOT NULL, "generatedConfig" text NOT NULL, "customParameters" text, "status" varchar CHECK( "status" IN ('generated','exported','applied','archived') ) NOT NULL DEFAULT ('generated'), "exportFormat" varchar CHECK( "exportFormat" IN ('json','yaml','env','shell_script') ), "exportedContent" text, "tags" text, "isFavorite" boolean NOT NULL DEFAULT (0), "usageCount" integer NOT NULL DEFAULT (0), "lastUsedAt" datetime, "createdBy" varchar(100), "notes" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "ai_assistant_configs"("id", "name", "description", "templateId", "generatedConfig", "customParameters", "status", "exportFormat", "exportedContent", "tags", "isFavorite", "usageCount", "lastUsedAt", "createdBy", "notes", "createdAt", "updatedAt") SELECT "id", "name", "description", "templateId", "generatedConfig", "customParameters", "status", "exportFormat", "exportedContent", "tags", "isFavorite", "usageCount", "lastUsedAt", "createdBy", "notes", "createdAt", "updatedAt" FROM "temporary_ai_assistant_configs"`);
        await queryRunner.query(`DROP TABLE "temporary_ai_assistant_configs"`);
        await queryRunner.query(`CREATE INDEX "IDX_0d12dfdffd091b709a66048207" ON "ai_assistant_configs" ("templateId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_05e34065f9197f0075ac77f780" ON "ai_assistant_configs" ("createdAt") `);
        await queryRunner.query(`DROP INDEX "IDX_3a1c8bcd8eb7820826c7073421"`);
        await queryRunner.query(`DROP INDEX "IDX_2d6a5bfe2bd723f1dc5752bacf"`);
        await queryRunner.query(`DROP INDEX "IDX_54a9714fc03cfc002e301b51f0"`);
        await queryRunner.query(`ALTER TABLE "openapi_documents" RENAME TO "temporary_openapi_documents"`);
        await queryRunner.query(`CREATE TABLE "openapi_documents" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "description" text, "content" text NOT NULL, "status" varchar CHECK( "status" IN ('draft','published','archived','valid','invalid','pending') ) NOT NULL DEFAULT ('draft'), "version" varchar(50) NOT NULL DEFAULT ('1.0.0'), "tags" text, "metadata" text, "user_id" varchar NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "openapi_documents"("id", "name", "description", "content", "status", "version", "tags", "metadata", "user_id", "createdAt", "updatedAt") SELECT "id", "name", "description", "content", "status", "version", "tags", "metadata", "user_id", "createdAt", "updatedAt" FROM "temporary_openapi_documents"`);
        await queryRunner.query(`DROP TABLE "temporary_openapi_documents"`);
        await queryRunner.query(`CREATE INDEX "IDX_3a1c8bcd8eb7820826c7073421" ON "openapi_documents" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d6a5bfe2bd723f1dc5752bacf" ON "openapi_documents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_54a9714fc03cfc002e301b51f0" ON "openapi_documents" ("createdAt") `);
        await queryRunner.query(`DROP INDEX "IDX_af8bc5ddf6bb239c2b40173a78"`);
        await queryRunner.query(`DROP INDEX "IDX_aa05ada70e2c999cde45172c90"`);
        await queryRunner.query(`DROP INDEX "IDX_a4d57d243d15a45c981aaab0e2"`);
        await queryRunner.query(`DROP INDEX "IDX_c6fb7db174ca4aa4d0033ab62b"`);
        await queryRunner.query(`DROP INDEX "IDX_8255879e189354927b5cd3186b"`);
        await queryRunner.query(`DROP INDEX "IDX_f4f5248b93c3ca62ed3761b30f"`);
        await queryRunner.query(`ALTER TABLE "system_logs" RENAME TO "temporary_system_logs"`);
        await queryRunner.query(`CREATE TABLE "system_logs" ("id" varchar PRIMARY KEY NOT NULL, "eventType" varchar CHECK( "eventType" IN ('server_started','server_stopped','server_restarted','server_crashed','server_timeout','server_created','server_updated','server_deleted','server_config_changed','connection_established','connection_lost','connection_retry','connection_failed','health_check_passed','health_check_failed','system_startup','system_shutdown','system_error') ) NOT NULL, "message" varchar(500), "description" text, "level" varchar CHECK( "level" IN ('debug','info','warning','error','critical') ) NOT NULL DEFAULT ('info'), "status" varchar CHECK( "status" IN ('success','failed','in_progress','cancelled') ) NOT NULL DEFAULT ('success'), "serverId" varchar(36), "serverName" varchar(255), "serverVersion" varchar(100), "serverPort" integer, "userId" varchar(36), "source" varchar(255), "context" text, "metadata" text, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "system_logs"("id", "eventType", "message", "description", "level", "status", "serverId", "serverName", "serverVersion", "serverPort", "userId", "source", "context", "metadata", "createdAt") SELECT "id", "eventType", "message", "description", "level", "status", "serverId", "serverName", "serverVersion", "serverPort", "userId", "source", "context", "metadata", "createdAt" FROM "temporary_system_logs"`);
        await queryRunner.query(`DROP TABLE "temporary_system_logs"`);
        await queryRunner.query(`CREATE INDEX "IDX_af8bc5ddf6bb239c2b40173a78" ON "system_logs" ("serverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa05ada70e2c999cde45172c90" ON "system_logs" ("eventType") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4d57d243d15a45c981aaab0e2" ON "system_logs" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6fb7db174ca4aa4d0033ab62b" ON "system_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8255879e189354927b5cd3186b" ON "system_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_f4f5248b93c3ca62ed3761b30f" ON "system_logs" ("userId") `);
        await queryRunner.query(`DROP INDEX "IDX_4542dd2f38a61354a040ba9fd5"`);
        await queryRunner.query(`DROP INDEX "IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP INDEX "IDX_56b91d98f71e3d1b649ed6e9f3"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" RENAME TO "temporary_refresh_tokens"`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" varchar PRIMARY KEY NOT NULL, "token" varchar(500) NOT NULL, "userId" varchar(36) NOT NULL, "expiresAt" datetime NOT NULL, "isRevoked" boolean NOT NULL DEFAULT (0), "deviceInfo" varchar(255), "ipAddress" varchar(45), "userAgent" varchar(500), "lastUsedAt" datetime, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "UQ_4542dd2f38a61354a040ba9fd57" UNIQUE ("token"))`);
        await queryRunner.query(`INSERT INTO "refresh_tokens"("id", "token", "userId", "expiresAt", "isRevoked", "deviceInfo", "ipAddress", "userAgent", "lastUsedAt", "createdAt", "updatedAt") SELECT "id", "token", "userId", "expiresAt", "isRevoked", "deviceInfo", "ipAddress", "userAgent", "lastUsedAt", "createdAt", "updatedAt" FROM "temporary_refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "temporary_refresh_tokens"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4542dd2f38a61354a040ba9fd5" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_56b91d98f71e3d1b649ed6e9f3" ON "refresh_tokens" ("expiresAt") `);
        await queryRunner.query(`DROP INDEX "IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP INDEX "IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "IDX_76566a7a3b90863650d467bff6"`);
        await queryRunner.query(`DROP INDEX "IDX_2961862b2704794af56359ff0a"`);
        await queryRunner.query(`DROP INDEX "IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "IDX_8ddc86298ac7fadad468b28d83"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" RENAME TO "temporary_audit_logs"`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" varchar PRIMARY KEY NOT NULL, "action" varchar CHECK( "action" IN ('user_login','user_logout','user_login_failed','user_created','user_updated','user_deleted','user_password_changed','user_role_assigned','user_role_removed','user_locked','user_unlocked','server_created','server_updated','server_deleted','server_started','server_stopped','server_restarted','api_called','api_configured','api_tested','config_updated','config_exported','config_imported','config_reset','permission_granted','permission_revoked','role_created','role_updated','role_deleted','api_key_created','api_key_deleted','api_key_used','system_backup','system_restore','system_maintenance') ) NOT NULL, "description" varchar(255), "level" varchar CHECK( "level" IN ('info','warning','error','critical') ) NOT NULL DEFAULT ('info'), "status" varchar CHECK( "status" IN ('success','failed','pending') ) NOT NULL DEFAULT ('success'), "resource" varchar(100), "resourceId" varchar(255), "ipAddress" varchar(45), "userAgent" varchar(500), "sessionId" varchar(255), "details" text, "metadata" text, "userId" varchar(36), "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "audit_logs"("id", "action", "description", "level", "status", "resource", "resourceId", "ipAddress", "userAgent", "sessionId", "details", "metadata", "userId", "createdAt") SELECT "id", "action", "description", "level", "status", "resource", "resourceId", "ipAddress", "userAgent", "sessionId", "details", "metadata", "userId", "createdAt" FROM "temporary_audit_logs"`);
        await queryRunner.query(`DROP TABLE "temporary_audit_logs"`);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_76566a7a3b90863650d467bff6" ON "audit_logs" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_2961862b2704794af56359ff0a" ON "audit_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_8ddc86298ac7fadad468b28d83" ON "audit_logs" ("ipAddress") `);
        await queryRunner.query(`DROP INDEX "IDX_c1544ddc5ab67b1c768ed74a5c"`);
        await queryRunner.query(`DROP INDEX "IDX_e01fae4223e72fdd0bba2e6f6a"`);
        await queryRunner.query(`DROP INDEX "IDX_bd0b54acd354a14abe257494e8"`);
        await queryRunner.query(`DROP INDEX "IDX_88410904513ed6cfdd598a777b"`);
        await queryRunner.query(`DROP INDEX "IDX_51bcf6d9189a9caa2956f7384d"`);
        await queryRunner.query(`ALTER TABLE "log_entries" RENAME TO "temporary_log_entries"`);
        await queryRunner.query(`CREATE TABLE "log_entries" ("id" varchar PRIMARY KEY NOT NULL, "level" varchar CHECK( "level" IN ('debug','info','warn','error','fatal') ) NOT NULL DEFAULT ('info'), "source" varchar CHECK( "source" IN ('system','mcp_server','api','tool_execution','auth','database','health_check') ) NOT NULL DEFAULT ('system'), "message" text NOT NULL, "context" text, "metadata" text, "serverId" varchar(36), "component" varchar(100), "operation" varchar(100), "stackTrace" text, "tags" text, "timestamp" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "log_entries"("id", "level", "source", "message", "context", "metadata", "serverId", "component", "operation", "stackTrace", "tags", "timestamp") SELECT "id", "level", "source", "message", "context", "metadata", "serverId", "component", "operation", "stackTrace", "tags", "timestamp" FROM "temporary_log_entries"`);
        await queryRunner.query(`DROP TABLE "temporary_log_entries"`);
        await queryRunner.query(`CREATE INDEX "IDX_c1544ddc5ab67b1c768ed74a5c" ON "log_entries" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_e01fae4223e72fdd0bba2e6f6a" ON "log_entries" ("source") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd0b54acd354a14abe257494e8" ON "log_entries" ("serverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_88410904513ed6cfdd598a777b" ON "log_entries" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_51bcf6d9189a9caa2956f7384d" ON "log_entries" ("level", "timestamp") `);
        await queryRunner.query(`DROP INDEX "IDX_a9f26e310a0af26792c8762d3b"`);
        await queryRunner.query(`ALTER TABLE "auth_configs" RENAME TO "temporary_auth_configs"`);
        await queryRunner.query(`CREATE TABLE "auth_configs" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar(255) NOT NULL, "description" text, "type" varchar CHECK( "type" IN ('none','bearer','apikey','basic','oauth2') ) NOT NULL DEFAULT ('none'), "config" text NOT NULL, "enabled" boolean NOT NULL DEFAULT (1), "expiresAt" datetime, "lastUsed" datetime, "serverId" varchar(36) NOT NULL, "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`INSERT INTO "auth_configs"("id", "name", "description", "type", "config", "enabled", "expiresAt", "lastUsed", "serverId", "createdAt", "updatedAt") SELECT "id", "name", "description", "type", "config", "enabled", "expiresAt", "lastUsed", "serverId", "createdAt", "updatedAt" FROM "temporary_auth_configs"`);
        await queryRunner.query(`DROP TABLE "temporary_auth_configs"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a9f26e310a0af26792c8762d3b" ON "auth_configs" ("serverId", "name") `);
        await queryRunner.query(`DROP INDEX "IDX_86033897c009fcca8b6505d6be"`);
        await queryRunner.query(`DROP INDEX "IDX_472b25323af01488f1f66a06b6"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "IDX_06792d0c62ce6b0203c03643cd"`);
        await queryRunner.query(`DROP INDEX "IDX_b4599f8b8f548d35850afa2d12"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "IDX_b94c9d86a0f5adda3d796f3e1c"`);
        await queryRunner.query(`DROP INDEX "IDX_e3f8f3f41a8bd665724bf9613d"`);
        await queryRunner.query(`DROP INDEX "IDX_7c0770c6fc1c6bb2d49f19bc44"`);
        await queryRunner.query(`DROP TABLE "runtime_verification_results"`);
        await queryRunner.query(`DROP INDEX "IDX_7621e2f741ca28bd3d948dca51"`);
        await queryRunner.query(`DROP INDEX "IDX_d19d1e5ac1f2ef9f95ae43199c"`);
        await queryRunner.query(`DROP INDEX "IDX_f1eb19f920ad31ee40dcfa4257"`);
        await queryRunner.query(`DROP TABLE "runtime_verification_runs"`);
        await queryRunner.query(`DROP INDEX "IDX_d99880dc022aa1ee886688e887"`);
        await queryRunner.query(`DROP INDEX "IDX_71d64ae3f496cedfc72e780331"`);
        await queryRunner.query(`DROP TABLE "runtime_upstream_binding_instances"`);
        await queryRunner.query(`DROP INDEX "IDX_ba9afe6c99646ad9d4728e63a3"`);
        await queryRunner.query(`DROP INDEX "IDX_96605e5f3fa22aebadcdc1ea44"`);
        await queryRunner.query(`DROP TABLE "runtime_upstream_bindings"`);
        await queryRunner.query(`DROP INDEX "IDX_ab7fff83ce10709684bd168008"`);
        await queryRunner.query(`DROP INDEX "IDX_f1479053976c4686906b199cb3"`);
        await queryRunner.query(`DROP INDEX "IDX_729ae6099b4bb9144f2639f819"`);
        await queryRunner.query(`DROP INDEX "IDX_8f854a950227a717bf6f726c09"`);
        await queryRunner.query(`DROP TABLE "endpoint_test_samples"`);
        await queryRunner.query(`DROP INDEX "IDX_c053461aadc401b6d584d493e3"`);
        await queryRunner.query(`DROP INDEX "IDX_ec7ed8579a9a2114ef1eb00a03"`);
        await queryRunner.query(`DROP INDEX "IDX_33b89528103648b88c7c86bb82"`);
        await queryRunner.query(`DROP TABLE "endpoint_test_runs"`);
        await queryRunner.query(`DROP INDEX "IDX_2ee693e52d2c1e4d465d532815"`);
        await queryRunner.query(`DROP TABLE "endpoint_test_cases"`);
        await queryRunner.query(`DROP INDEX "IDX_0f92e685581c791458b6c8af68"`);
        await queryRunner.query(`DROP INDEX "IDX_bd1964571f38932f02b96aebd8"`);
        await queryRunner.query(`DROP INDEX "IDX_f390aaa00963aaf930b7f96f51"`);
        await queryRunner.query(`DROP TABLE "source_service_instances"`);
        await queryRunner.query(`DROP INDEX "IDX_0d12dfdffd091b709a66048207"`);
        await queryRunner.query(`DROP INDEX "IDX_05e34065f9197f0075ac77f780"`);
        await queryRunner.query(`DROP TABLE "ai_assistant_configs"`);
        await queryRunner.query(`DROP INDEX "IDX_808d57a7a3e56bc043eba39545"`);
        await queryRunner.query(`DROP INDEX "IDX_671f38118641e729c0b7669958"`);
        await queryRunner.query(`DROP TABLE "ai_assistant_templates"`);
        await queryRunner.query(`DROP INDEX "IDX_31dbfa87d727d5981ed35a515c"`);
        await queryRunner.query(`DROP INDEX "IDX_2635524c23c3528325712110f5"`);
        await queryRunner.query(`DROP INDEX "IDX_1ad7e7f3f31d107e86154c8530"`);
        await queryRunner.query(`DROP INDEX "IDX_b9b1ccce1eeb77c96ca75d4c48"`);
        await queryRunner.query(`DROP INDEX "IDX_421c630442a8b8b7a7bc12d6e8"`);
        await queryRunner.query(`DROP TABLE "runtime_observability_states"`);
        await queryRunner.query(`DROP INDEX "IDX_1e1d57f7b6a4c739aa460fed3d"`);
        await queryRunner.query(`DROP INDEX "IDX_ae4b736e4d2b58d32b5095b7ca"`);
        await queryRunner.query(`DROP INDEX "IDX_5d2bb27857d9aaafbefa3c2852"`);
        await queryRunner.query(`DROP INDEX "IDX_cd73b7b0cf638d5b3113d9d131"`);
        await queryRunner.query(`DROP INDEX "IDX_811dbf17e22bf3f4bc0f30e47b"`);
        await queryRunner.query(`DROP INDEX "IDX_2eba4d2d1deb7439058411b5ba"`);
        await queryRunner.query(`DROP TABLE "runtime_observability_events"`);
        await queryRunner.query(`DROP INDEX "IDX_c59ed6275e5eaa43201959d4c5"`);
        await queryRunner.query(`DROP INDEX "IDX_4a1e48002f71ed0d77ef861ce8"`);
        await queryRunner.query(`DROP INDEX "IDX_9b2140172938601a458984f864"`);
        await queryRunner.query(`DROP INDEX "IDX_898a4704bf170f0b4e7bee4ee8"`);
        await queryRunner.query(`DROP TABLE "runtime_metric_series"`);
        await queryRunner.query(`DROP INDEX "IDX_c442960f31c4b3043466f8da08"`);
        await queryRunner.query(`DROP INDEX "IDX_c54532f858d1c223d40a6d821f"`);
        await queryRunner.query(`DROP INDEX "IDX_c1be17115c8ddd7233657265e8"`);
        await queryRunner.query(`DROP INDEX "IDX_0e8340ccffe02d565eed3a4364"`);
        await queryRunner.query(`DROP TABLE "gateway_consumer_credentials"`);
        await queryRunner.query(`DROP INDEX "IDX_f3a4c2124d3a09a1830f500dab"`);
        await queryRunner.query(`DROP INDEX "IDX_0a339d1242fc2d87f80f5b352c"`);
        await queryRunner.query(`DROP INDEX "IDX_72f0530d4cdcc947e2e33406d1"`);
        await queryRunner.query(`DROP INDEX "IDX_f787ee33e930a71a010e53c654"`);
        await queryRunner.query(`DROP INDEX "IDX_eaf52dad83edc21428b3fa1b32"`);
        await queryRunner.query(`DROP INDEX "IDX_1abedaf643842a1ebeff5e93ac"`);
        await queryRunner.query(`DROP TABLE "gateway_access_logs"`);
        await queryRunner.query(`DROP INDEX "IDX_6d7b04e03e153afceed995acc4"`);
        await queryRunner.query(`DROP INDEX "IDX_85c75b677c5c10bc99022797ef"`);
        await queryRunner.query(`DROP INDEX "IDX_88d90bbe4eb5113863828bd2d1"`);
        await queryRunner.query(`DROP INDEX "IDX_f2b83bb98b3a6ecf8fcb01c724"`);
        await queryRunner.query(`DROP INDEX "IDX_a61ea3be16d7b504d37ea68a41"`);
        await queryRunner.query(`DROP INDEX "IDX_6e0221c655506d503484cf52e8"`);
        await queryRunner.query(`DROP TABLE "gateway_route_snapshots"`);
        await queryRunner.query(`DROP TABLE "gateway_route_bindings"`);
        await queryRunner.query(`DROP INDEX "IDX_bf37d3b26bafade0d4d6385bc4"`);
        await queryRunner.query(`DROP INDEX "IDX_7a27af3b2b163918115580578f"`);
        await queryRunner.query(`DROP INDEX "IDX_a14db7f1483330b431c99b27e8"`);
        await queryRunner.query(`DROP TABLE "endpoint_publish_bindings"`);
        await queryRunner.query(`DROP INDEX "IDX_f9021e17e279724424f99986fd"`);
        await queryRunner.query(`DROP INDEX "IDX_3f8bbcb256a405eab0007a5a5b"`);
        await queryRunner.query(`DROP INDEX "IDX_978a210f3599c1c7423182f779"`);
        await queryRunner.query(`DROP INDEX "IDX_93c4ebca8d35af690a10753064"`);
        await queryRunner.query(`DROP INDEX "IDX_e799fc3632f5bde1659207f6b5"`);
        await queryRunner.query(`DROP INDEX "IDX_2d1925c76e38c461873d8f078d"`);
        await queryRunner.query(`DROP TABLE "publication_audit_events"`);
        await queryRunner.query(`DROP INDEX "IDX_229bf64062d89f697420effc81"`);
        await queryRunner.query(`DROP INDEX "IDX_7e2e4a7e91c2e069847b69c2ba"`);
        await queryRunner.query(`DROP INDEX "IDX_71184961a966965f2d1a07ab08"`);
        await queryRunner.query(`DROP INDEX "IDX_d380c8ad525ed6964b0cd3872a"`);
        await queryRunner.query(`DROP TABLE "publication_batch_runs"`);
        await queryRunner.query(`DROP INDEX "IDX_53f90e5c9c8544c0a427c1dcfe"`);
        await queryRunner.query(`DROP INDEX "IDX_b731eef4efcd5f4013ae908082"`);
        await queryRunner.query(`DROP INDEX "IDX_6be2440698e2376a5f2e84c249"`);
        await queryRunner.query(`DROP TABLE "publication_profile_history"`);
        await queryRunner.query(`DROP INDEX "IDX_700ab179bf73420e265595a3a6"`);
        await queryRunner.query(`DROP INDEX "IDX_48c1bcc4789a93a9b03d7f8a10"`);
        await queryRunner.query(`DROP INDEX "IDX_3f1d3709f4e13fdd17fb4524be"`);
        await queryRunner.query(`DROP INDEX "IDX_f6f63d557a6caa1ff1bb69e464"`);
        await queryRunner.query(`DROP INDEX "IDX_0bcb384804888966597b29e249"`);
        await queryRunner.query(`DROP TABLE "publication_profiles"`);
        await queryRunner.query(`DROP INDEX "IDX_efb699533b2cc4e467a6c428cf"`);
        await queryRunner.query(`DROP INDEX "IDX_4e712a424ce528e5c8116ca50f"`);
        await queryRunner.query(`DROP TABLE "runtime_asset_endpoint_bindings"`);
        await queryRunner.query(`DROP INDEX "IDX_a1892cfa29a4fdf4ee960c1a4b"`);
        await queryRunner.query(`DROP INDEX "IDX_91af03862e2573dcde1f9dc54f"`);
        await queryRunner.query(`DROP TABLE "runtime_assets"`);
        await queryRunner.query(`DROP INDEX "IDX_ebe74ec16bc2db7f76a4c662bf"`);
        await queryRunner.query(`DROP INDEX "IDX_795989a35d91fe69aedeaa01a3"`);
        await queryRunner.query(`DROP TABLE "endpoint_definitions"`);
        await queryRunner.query(`DROP INDEX "IDX_003e5cc6b79472ad6baaa33162"`);
        await queryRunner.query(`DROP TABLE "source_service_assets"`);
        await queryRunner.query(`DROP INDEX "IDX_3a1c8bcd8eb7820826c7073421"`);
        await queryRunner.query(`DROP INDEX "IDX_2d6a5bfe2bd723f1dc5752bacf"`);
        await queryRunner.query(`DROP INDEX "IDX_54a9714fc03cfc002e301b51f0"`);
        await queryRunner.query(`DROP TABLE "openapi_documents"`);
        await queryRunner.query(`DROP INDEX "IDX_af8bc5ddf6bb239c2b40173a78"`);
        await queryRunner.query(`DROP INDEX "IDX_aa05ada70e2c999cde45172c90"`);
        await queryRunner.query(`DROP INDEX "IDX_a4d57d243d15a45c981aaab0e2"`);
        await queryRunner.query(`DROP INDEX "IDX_c6fb7db174ca4aa4d0033ab62b"`);
        await queryRunner.query(`DROP INDEX "IDX_8255879e189354927b5cd3186b"`);
        await queryRunner.query(`DROP INDEX "IDX_f4f5248b93c3ca62ed3761b30f"`);
        await queryRunner.query(`DROP TABLE "system_logs"`);
        await queryRunner.query(`DROP INDEX "IDX_4542dd2f38a61354a040ba9fd5"`);
        await queryRunner.query(`DROP INDEX "IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP INDEX "IDX_56b91d98f71e3d1b649ed6e9f3"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP INDEX "IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "IDX_76566a7a3b90863650d467bff6"`);
        await queryRunner.query(`DROP INDEX "IDX_2961862b2704794af56359ff0a"`);
        await queryRunner.query(`DROP INDEX "IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "IDX_8ddc86298ac7fadad468b28d83"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "IDX_48ce552495d14eae9b187bb671"`);
        await queryRunner.query(`DROP INDEX "IDX_6cf44c88049465f900899da21e"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "IDX_c1544ddc5ab67b1c768ed74a5c"`);
        await queryRunner.query(`DROP INDEX "IDX_e01fae4223e72fdd0bba2e6f6a"`);
        await queryRunner.query(`DROP INDEX "IDX_bd0b54acd354a14abe257494e8"`);
        await queryRunner.query(`DROP INDEX "IDX_88410904513ed6cfdd598a777b"`);
        await queryRunner.query(`DROP INDEX "IDX_51bcf6d9189a9caa2956f7384d"`);
        await queryRunner.query(`DROP TABLE "log_entries"`);
        await queryRunner.query(`DROP INDEX "IDX_a9f26e310a0af26792c8762d3b"`);
        await queryRunner.query(`DROP TABLE "auth_configs"`);
        await queryRunner.query(`DROP INDEX "IDX_2ee0138f3dd9575eedd37f2405"`);
        await queryRunner.query(`DROP INDEX "IDX_7ed02efd17d98567e515642eb0"`);
        await queryRunner.query(`DROP TABLE "mcp_servers"`);
    }

}
