import { MigrationInterface, QueryRunner } from "typeorm";

export class CanonicalPostgresBaseline1784649376851 implements MigrationInterface {
    name = 'CanonicalPostgresBaseline1784649376851'

    public async up(queryRunner: QueryRunner): Promise<void> {
        if (queryRunner.connection.options.type !== 'postgres') return;
        await queryRunner.query(`CREATE TYPE "public"."mcp_servers_transport_enum" AS ENUM('streamable', 'sse')`);
        await queryRunner.query(`CREATE TYPE "public"."mcp_servers_status_enum" AS ENUM('stopped', 'starting', 'running', 'stopping', 'error')`);
        await queryRunner.query(`CREATE TABLE "mcp_servers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "version" character varying(100) NOT NULL DEFAULT '1.0.0', "description" text, "port" integer NOT NULL DEFAULT '9022', "transport" "public"."mcp_servers_transport_enum" NOT NULL DEFAULT 'streamable', "status" "public"."mcp_servers_status_enum" NOT NULL DEFAULT 'stopped', "endpoint" text, "openApiData" jsonb NOT NULL, "tools" jsonb, "toolsCount" integer NOT NULL DEFAULT '0', "config" jsonb, "authConfig" jsonb, "lastHealthCheck" TIMESTAMP, "healthy" boolean NOT NULL DEFAULT true, "errorMessage" text, "metrics" jsonb, "autoStart" boolean NOT NULL DEFAULT true, "tags" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2ee0138f3dd9575eedd37f2405f" UNIQUE ("name"), CONSTRAINT "PK_c781b3dc7cb2a5d19460b71914d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7ed02efd17d98567e515642eb0" ON "mcp_servers" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2ee0138f3dd9575eedd37f2405" ON "mcp_servers" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."auth_configs_type_enum" AS ENUM('none', 'bearer', 'apikey', 'basic', 'oauth2')`);
        await queryRunner.query(`CREATE TABLE "auth_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "type" "public"."auth_configs_type_enum" NOT NULL DEFAULT 'none', "config" jsonb NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "expiresAt" TIMESTAMP, "lastUsed" TIMESTAMP, "serverId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5178fc2503176ad72a3280442ac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a9f26e310a0af26792c8762d3b" ON "auth_configs" ("serverId", "name") `);
        await queryRunner.query(`CREATE TYPE "public"."log_entries_level_enum" AS ENUM('debug', 'info', 'warn', 'error', 'fatal')`);
        await queryRunner.query(`CREATE TYPE "public"."log_entries_source_enum" AS ENUM('system', 'mcp_server', 'api', 'tool_execution', 'auth', 'database', 'health_check')`);
        await queryRunner.query(`CREATE TABLE "log_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "level" "public"."log_entries_level_enum" NOT NULL DEFAULT 'info', "source" "public"."log_entries_source_enum" NOT NULL DEFAULT 'system', "message" text NOT NULL, "context" jsonb, "metadata" jsonb, "serverId" uuid, "component" character varying(100), "operation" character varying(100), "stackTrace" text, "tags" jsonb, "timestamp" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b226cc4051321f12106771581e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_51bcf6d9189a9caa2956f7384d" ON "log_entries" ("level", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_88410904513ed6cfdd598a777b" ON "log_entries" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd0b54acd354a14abe257494e8" ON "log_entries" ("serverId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e01fae4223e72fdd0bba2e6f6a" ON "log_entries" ("source") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1544ddc5ab67b1c768ed74a5c" ON "log_entries" ("level") `);
        await queryRunner.query(`CREATE TYPE "public"."permissions_category_enum" AS ENUM('system', 'user_management', 'server_management', 'api_management', 'monitoring', 'configuration', 'security', 'audit')`);
        await queryRunner.query(`CREATE TYPE "public"."permissions_action_enum" AS ENUM('create', 'read', 'update', 'delete', 'execute', 'manage', 'view', 'export', 'import')`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" character varying(255), "category" "public"."permissions_category_enum" NOT NULL, "action" "public"."permissions_action_enum" NOT NULL, "resource" character varying(100), "enabled" boolean NOT NULL DEFAULT true, "isSystem" boolean NOT NULL DEFAULT false, "conditions" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6cf44c88049465f900899da21e" ON "permissions" ("category", "action") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_48ce552495d14eae9b187bb671" ON "permissions" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."roles_type_enum" AS ENUM('system', 'admin', 'user', 'custom')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" character varying(255), "type" "public"."roles_type_enum" NOT NULL DEFAULT 'custom', "enabled" boolean NOT NULL DEFAULT true, "isDefault" boolean NOT NULL DEFAULT false, "priority" integer NOT NULL DEFAULT '0', "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('user_login', 'user_logout', 'user_login_failed', 'user_created', 'user_updated', 'user_deleted', 'user_password_changed', 'user_role_assigned', 'user_role_removed', 'user_locked', 'user_unlocked', 'server_created', 'server_updated', 'server_deleted', 'server_started', 'server_stopped', 'server_restarted', 'api_called', 'api_configured', 'api_tested', 'config_updated', 'config_exported', 'config_imported', 'config_reset', 'permission_granted', 'permission_revoked', 'role_created', 'role_updated', 'role_deleted', 'api_key_created', 'api_key_deleted', 'api_key_used', 'system_backup', 'system_restore', 'system_maintenance')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_level_enum" AS ENUM('info', 'warning', 'error', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_status_enum" AS ENUM('success', 'failed', 'pending')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" "public"."audit_logs_action_enum" NOT NULL, "description" character varying(255), "level" "public"."audit_logs_level_enum" NOT NULL DEFAULT 'info', "status" "public"."audit_logs_status_enum" NOT NULL DEFAULT 'success', "resource" character varying(100), "resourceId" character varying(255), "ipAddress" inet, "userAgent" character varying(500), "sessionId" character varying(255), "details" jsonb, "metadata" jsonb, "userId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8ddc86298ac7fadad468b28d83" ON "audit_logs" ("ipAddress") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2961862b2704794af56359ff0a" ON "audit_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_76566a7a3b90863650d467bff6" ON "audit_logs" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_cfa83f61e4d27a87fcae1e025a" ON "audit_logs" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended', 'pending')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "password" character varying(255) NOT NULL, "firstName" character varying(100), "lastName" character varying(100), "status" "public"."users_status_enum" NOT NULL DEFAULT 'pending', "emailVerified" boolean NOT NULL DEFAULT false, "emailVerificationToken" character varying(255), "passwordResetToken" character varying(255), "passwordResetExpires" TIMESTAMP, "lastLoginAt" TIMESTAMP, "lastLoginIp" inet, "loginAttempts" integer NOT NULL DEFAULT '0', "lockedUntil" TIMESTAMP, "preferences" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying(500) NOT NULL, "userId" uuid NOT NULL, "expiresAt" TIMESTAMP NOT NULL, "isRevoked" boolean NOT NULL DEFAULT false, "deviceInfo" character varying(255), "ipAddress" inet, "userAgent" character varying(500), "lastUsedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4542dd2f38a61354a040ba9fd57" UNIQUE ("token"), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_56b91d98f71e3d1b649ed6e9f3" ON "refresh_tokens" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_610102b60fea1455310ccd299d" ON "refresh_tokens" ("userId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4542dd2f38a61354a040ba9fd5" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE TYPE "public"."system_logs_eventtype_enum" AS ENUM('server_started', 'server_stopped', 'server_restarted', 'server_crashed', 'server_timeout', 'server_created', 'server_updated', 'server_deleted', 'server_config_changed', 'connection_established', 'connection_lost', 'connection_retry', 'connection_failed', 'health_check_passed', 'health_check_failed', 'system_startup', 'system_shutdown', 'system_error')`);
        await queryRunner.query(`CREATE TYPE "public"."system_logs_level_enum" AS ENUM('debug', 'info', 'warning', 'error', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."system_logs_status_enum" AS ENUM('success', 'failed', 'in_progress', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "system_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "eventType" "public"."system_logs_eventtype_enum" NOT NULL, "message" character varying(500), "description" text, "level" "public"."system_logs_level_enum" NOT NULL DEFAULT 'info', "status" "public"."system_logs_status_enum" NOT NULL DEFAULT 'success', "serverId" uuid, "serverName" character varying(255), "serverVersion" character varying(100), "serverPort" integer, "userId" uuid, "source" character varying(255), "context" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_56861c4b9d16aa90259f4ce0a2c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f4f5248b93c3ca62ed3761b30f" ON "system_logs" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_8255879e189354927b5cd3186b" ON "system_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c6fb7db174ca4aa4d0033ab62b" ON "system_logs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4d57d243d15a45c981aaab0e2" ON "system_logs" ("level") `);
        await queryRunner.query(`CREATE INDEX "IDX_aa05ada70e2c999cde45172c90" ON "system_logs" ("eventType") `);
        await queryRunner.query(`CREATE INDEX "IDX_af8bc5ddf6bb239c2b40173a78" ON "system_logs" ("serverId") `);
        await queryRunner.query(`CREATE TYPE "public"."openapi_documents_status_enum" AS ENUM('draft', 'published', 'archived', 'valid', 'invalid', 'pending')`);
        await queryRunner.query(`CREATE TABLE "openapi_documents" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "content" text NOT NULL, "status" "public"."openapi_documents_status_enum" NOT NULL DEFAULT 'draft', "version" character varying(50) NOT NULL DEFAULT '1.0.0', "tags" text, "metadata" jsonb, "user_id" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d78a8bac2ec944771ada39b96c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_54a9714fc03cfc002e301b51f0" ON "openapi_documents" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d6a5bfe2bd723f1dc5752bacf" ON "openapi_documents" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_3a1c8bcd8eb7820826c7073421" ON "openapi_documents" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "source_service_assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sourceKey" character varying(255) NOT NULL, "displayName" character varying(255), "description" text, "owner" character varying(255), "tags" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5c3b9d682ba1547cedc21854930" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_003e5cc6b79472ad6baaa33162" ON "source_service_assets" ("sourceKey") `);
        await queryRunner.query(`CREATE TYPE "public"."endpoint_definitions_status_enum" AS ENUM('draft', 'verified', 'published', 'degraded', 'offline', 'retired')`);
        await queryRunner.query(`CREATE TABLE "endpoint_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sourceServiceAssetId" character varying(36) NOT NULL, "method" character varying(16) NOT NULL, "path" character varying(1024) NOT NULL, "operationId" character varying(255), "summary" character varying(255), "description" text, "status" "public"."endpoint_definitions_status_enum" NOT NULL DEFAULT 'draft', "publishEnabled" boolean NOT NULL DEFAULT false, "rawOperation" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1428aca6ee3f322cbffa3cc247e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_795989a35d91fe69aedeaa01a3" ON "endpoint_definitions" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ebe74ec16bc2db7f76a4c662bf" ON "endpoint_definitions" ("sourceServiceAssetId", "method", "path") `);
        await queryRunner.query(`CREATE TYPE "public"."runtime_assets_type_enum" AS ENUM('mcp_server', 'gateway_service')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_assets_status_enum" AS ENUM('draft', 'active', 'degraded', 'offline')`);
        await queryRunner.query(`CREATE TABLE "runtime_assets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "type" "public"."runtime_assets_type_enum" NOT NULL, "status" "public"."runtime_assets_status_enum" NOT NULL DEFAULT 'draft', "displayName" character varying(255), "description" text, "policyBindingRef" character varying(100), "servicePrefix" character varying(120), "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_a1892cfa29a4fdf4ee960c1a4bc" UNIQUE ("name"), CONSTRAINT "PK_eae4a5173992df3905c30997109" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_91af03862e2573dcde1f9dc54f" ON "runtime_assets" ("type", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a1892cfa29a4fdf4ee960c1a4b" ON "runtime_assets" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."runtime_asset_endpoint_bindings_status_enum" AS ENUM('draft', 'active', 'offline')`);
        await queryRunner.query(`CREATE TABLE "runtime_asset_endpoint_bindings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "runtimeAssetId" character varying(36) NOT NULL, "endpointDefinitionId" character varying(36) NOT NULL, "status" "public"."runtime_asset_endpoint_bindings_status_enum" NOT NULL DEFAULT 'draft', "publicationRevision" integer NOT NULL DEFAULT '0', "enabled" boolean NOT NULL DEFAULT true, "bindingConfig" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_204ad2c7cd09fb4ffbe24c58e3e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4e712a424ce528e5c8116ca50f" ON "runtime_asset_endpoint_bindings" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_efb699533b2cc4e467a6c428cf" ON "runtime_asset_endpoint_bindings" ("runtimeAssetId", "endpointDefinitionId") `);
        await queryRunner.query(`CREATE TYPE "public"."publication_profiles_status_enum" AS ENUM('draft', 'reviewed', 'published', 'offline')`);
        await queryRunner.query(`CREATE TABLE "publication_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "endpointDefinitionId" character varying(36) NOT NULL, "runtimeAssetEndpointBindingId" character varying(36), "version" integer NOT NULL DEFAULT '1', "intentName" character varying(255), "descriptionForLlm" text, "operatorNotes" text, "inputAliases" jsonb, "constraints" jsonb, "examples" jsonb, "visibility" character varying(32) NOT NULL DEFAULT 'internal', "status" "public"."publication_profiles_status_enum" NOT NULL DEFAULT 'draft', "draftSource" character varying(32), "createdBy" character varying(36), "updatedBy" character varying(36), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8d55094a8c7140cd3033f9e2b27" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0bcb384804888966597b29e249" ON "publication_profiles" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_f6f63d557a6caa1ff1bb69e464" ON "publication_profiles" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3f1d3709f4e13fdd17fb4524be" ON "publication_profiles" ("runtimeAssetEndpointBindingId", "version") `);
        await queryRunner.query(`CREATE INDEX "IDX_48c1bcc4789a93a9b03d7f8a10" ON "publication_profiles" ("endpointDefinitionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_700ab179bf73420e265595a3a6" ON "publication_profiles" ("endpointDefinitionId", "version") `);
        await queryRunner.query(`CREATE TABLE "publication_profile_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "endpointDefinitionId" character varying(36) NOT NULL, "runtimeAssetEndpointBindingId" character varying(36), "publicationProfileId" character varying(36) NOT NULL, "version" integer NOT NULL, "snapshot" jsonb NOT NULL, "action" character varying(64) NOT NULL, "actorId" character varying(36), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e57483762fe805ae8039abe51e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6be2440698e2376a5f2e84c249" ON "publication_profile_history" ("publicationProfileId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b731eef4efcd5f4013ae908082" ON "publication_profile_history" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_53f90e5c9c8544c0a427c1dcfe" ON "publication_profile_history" ("endpointDefinitionId") `);
        await queryRunner.query(`CREATE TYPE "public"."publication_batch_runs_action_enum" AS ENUM('publish', 'offline')`);
        await queryRunner.query(`CREATE TYPE "public"."publication_batch_runs_status_enum" AS ENUM('pending', 'success', 'partial', 'failed')`);
        await queryRunner.query(`CREATE TABLE "publication_batch_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" "public"."publication_batch_runs_action_enum" NOT NULL, "status" "public"."publication_batch_runs_status_enum" NOT NULL DEFAULT 'pending', "runtimeAssetId" character varying(36), "runtimeAssetType" character varying(32), "totalCount" integer NOT NULL DEFAULT '0', "successCount" integer NOT NULL DEFAULT '0', "failedCount" integer NOT NULL DEFAULT '0', "operatorId" character varying(36), "triggerSource" character varying(32) NOT NULL DEFAULT 'publication-ui', "requestPayload" jsonb, "resultSummary" jsonb, "startedAt" TIMESTAMP NOT NULL, "finishedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_68793830913b8772483a49a1916" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d380c8ad525ed6964b0cd3872a" ON "publication_batch_runs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_71184961a966965f2d1a07ab08" ON "publication_batch_runs" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e2e4a7e91c2e069847b69c2ba" ON "publication_batch_runs" ("operatorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_229bf64062d89f697420effc81" ON "publication_batch_runs" ("runtimeAssetId") `);
        await queryRunner.query(`CREATE TYPE "public"."publication_audit_events_action_enum" AS ENUM('runtime_asset.created', 'memberships.added', 'profile.updated', 'gateway_route.updated', 'membership.published', 'membership.offlined', 'batch.publish', 'batch.offline')`);
        await queryRunner.query(`CREATE TYPE "public"."publication_audit_events_status_enum" AS ENUM('success', 'partial', 'failed', 'info')`);
        await queryRunner.query(`CREATE TABLE "publication_audit_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "action" "public"."publication_audit_events_action_enum" NOT NULL, "status" "public"."publication_audit_events_status_enum" NOT NULL DEFAULT 'info', "summary" character varying(255) NOT NULL, "details" jsonb, "publicationBatchRunId" character varying(36), "runtimeAssetId" character varying(36), "runtimeAssetEndpointBindingId" character varying(36), "endpointDefinitionId" character varying(36), "sourceServiceAssetId" character varying(36), "operatorId" character varying(36), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_52bd578e9a60e279d7be2f95124" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2d1925c76e38c461873d8f078d" ON "publication_audit_events" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_e799fc3632f5bde1659207f6b5" ON "publication_audit_events" ("operatorId") `);
        await queryRunner.query(`CREATE INDEX "IDX_93c4ebca8d35af690a10753064" ON "publication_audit_events" ("endpointDefinitionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_978a210f3599c1c7423182f779" ON "publication_audit_events" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3f8bbcb256a405eab0007a5a5b" ON "publication_audit_events" ("runtimeAssetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f9021e17e279724424f99986fd" ON "publication_audit_events" ("publicationBatchRunId") `);
        await queryRunner.query(`CREATE TYPE "public"."endpoint_publish_bindings_reviewstatus_enum" AS ENUM('pending', 'reviewed', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."endpoint_publish_bindings_publishstatus_enum" AS ENUM('draft', 'active', 'offline')`);
        await queryRunner.query(`CREATE TABLE "endpoint_publish_bindings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "endpointDefinitionId" character varying(36) NOT NULL, "runtimeAssetEndpointBindingId" character varying(36), "publicationProfileId" character varying(36), "publicationRevision" integer NOT NULL DEFAULT '0', "reviewStatus" "public"."endpoint_publish_bindings_reviewstatus_enum" NOT NULL DEFAULT 'pending', "publishStatus" "public"."endpoint_publish_bindings_publishstatus_enum" NOT NULL DEFAULT 'draft', "publishedToMcp" boolean NOT NULL DEFAULT false, "publishedToHttp" boolean NOT NULL DEFAULT false, "publishedAt" TIMESTAMP, "publishedBy" character varying(36), "offlineAt" TIMESTAMP, "offlineBy" character varying(36), "lastSnapshotId" character varying(36), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d71b1f651e378e64bbbc78a3923" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a14db7f1483330b431c99b27e8" ON "endpoint_publish_bindings" ("publishStatus") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_7a27af3b2b163918115580578f" ON "endpoint_publish_bindings" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bf37d3b26bafade0d4d6385bc4" ON "endpoint_publish_bindings" ("endpointDefinitionId") `);
        await queryRunner.query(`CREATE TYPE "public"."gateway_route_bindings_pathmatchmode_enum" AS ENUM('exact', 'prefix', 'parameter')`);
        await queryRunner.query(`CREATE TYPE "public"."gateway_route_bindings_status_enum" AS ENUM('draft', 'active', 'offline')`);
        await queryRunner.query(`CREATE TABLE "gateway_route_bindings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "endpointDefinitionId" character varying(36) NOT NULL, "runtimeAssetEndpointBindingId" character varying(36), "publishBindingId" character varying(36), "routePath" character varying(255) NOT NULL, "matchHost" character varying(255), "pathMatchMode" "public"."gateway_route_bindings_pathmatchmode_enum" NOT NULL DEFAULT 'exact', "priority" integer NOT NULL DEFAULT '0', "upstreamPath" character varying(255) NOT NULL, "routeMethod" character varying(16) NOT NULL, "upstreamMethod" character varying(16) NOT NULL, "routeVisibility" character varying(32) NOT NULL DEFAULT 'internal', "authPolicyRef" character varying(100), "trafficPolicyRef" character varying(100), "loggingPolicyRef" character varying(100), "cachePolicyRef" character varying(100), "rateLimitPolicyRef" character varying(100), "circuitBreakerPolicyRef" character varying(100), "timeoutMs" integer, "retryPolicy" jsonb, "upstreamConfig" jsonb, "routeStatusReason" text, "status" "public"."gateway_route_bindings_status_enum" NOT NULL DEFAULT 'draft', "lastPublishedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b5e7c462aac92ae9a9fa7dabd46" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f2b83bb98b3a6ecf8fcb01c724" ON "gateway_route_bindings" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_88d90bbe4eb5113863828bd2d1" ON "gateway_route_bindings" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_85c75b677c5c10bc99022797ef" ON "gateway_route_bindings" ("endpointDefinitionId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6d7b04e03e153afceed995acc4" ON "gateway_route_bindings" ("matchHost", "routePath", "routeMethod") `);
        await queryRunner.query(`CREATE TABLE "gateway_route_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "runtimeAssetId" character varying(36) NOT NULL, "revision" character varying(64) NOT NULL, "fingerprint" character varying(64) NOT NULL, "routeCount" integer NOT NULL DEFAULT '0', "payload" jsonb NOT NULL, "activatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5170c23a956af18a3e66270d86c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6e0221c655506d503484cf52e8" ON "gateway_route_snapshots" ("runtimeAssetId", "activatedAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a61ea3be16d7b504d37ea68a41" ON "gateway_route_snapshots" ("runtimeAssetId", "revision") `);
        await queryRunner.query(`CREATE TABLE "gateway_access_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "requestId" character varying(120) NOT NULL, "correlationId" character varying(120), "runtimeAssetId" uuid, "runtimeMembershipId" uuid, "routeBindingId" uuid, "endpointDefinitionId" uuid, "method" character varying(16) NOT NULL, "routePath" character varying(255) NOT NULL, "upstreamUrl" text, "statusCode" integer, "latencyMs" integer, "clientIp" character varying(45), "actorId" uuid, "authMode" character varying(32), "consumerId" uuid, "credentialKeyId" character varying(120), "requestContentType" character varying(255), "responseContentType" character varying(255), "requestBytes" bigint, "responseBytes" bigint, "requestHeaders" jsonb, "responseHeaders" jsonb, "requestQuery" jsonb, "requestBodyPreview" text, "responseBodyPreview" text, "requestBodyHash" character varying(128), "responseBodyHash" character varying(128), "captureMode" character varying(32) NOT NULL DEFAULT 'meta_only', "errorMessage" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1cb1d78f8e4a3757294d4a680cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1abedaf643842a1ebeff5e93ac" ON "gateway_access_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_eaf52dad83edc21428b3fa1b32" ON "gateway_access_logs" ("statusCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_f787ee33e930a71a010e53c654" ON "gateway_access_logs" ("routeBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_72f0530d4cdcc947e2e33406d1" ON "gateway_access_logs" ("runtimeMembershipId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0a339d1242fc2d87f80f5b352c" ON "gateway_access_logs" ("runtimeAssetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f3a4c2124d3a09a1830f500dab" ON "gateway_access_logs" ("requestId") `);
        await queryRunner.query(`CREATE TYPE "public"."gateway_consumer_credentials_status_enum" AS ENUM('active', 'inactive', 'revoked')`);
        await queryRunner.query(`CREATE TABLE "gateway_consumer_credentials" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(120) NOT NULL, "keyId" character varying(120) NOT NULL, "secretHash" character varying(128) NOT NULL, "label" character varying(255), "status" "public"."gateway_consumer_credentials_status_enum" NOT NULL DEFAULT 'active', "runtimeAssetId" character varying(36), "routeBindingId" character varying(36), "metadata" jsonb, "lastUsedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c442960f31c4b3043466f8da08b" UNIQUE ("keyId"), CONSTRAINT "PK_b9d11933fbaf6fb1acc041b6a39" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0e8340ccffe02d565eed3a4364" ON "gateway_consumer_credentials" ("routeBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c1be17115c8ddd7233657265e8" ON "gateway_consumer_credentials" ("runtimeAssetId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c54532f858d1c223d40a6d821f" ON "gateway_consumer_credentials" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c442960f31c4b3043466f8da08" ON "gateway_consumer_credentials" ("keyId") `);
        await queryRunner.query(`CREATE TYPE "public"."runtime_metric_series_metricscope_enum" AS ENUM('runtime_asset', 'runtime_membership', 'endpoint_definition', 'source_service_asset', 'system')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_metric_series_aggregationwindow_enum" AS ENUM('minute', 'five_minutes', 'hour', 'day')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_metric_series_metrictype_enum" AS ENUM('counter', 'gauge', 'histogram', 'rate')`);
        await queryRunner.query(`CREATE TABLE "runtime_metric_series" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "runtimeAssetId" character varying(36), "runtimeAssetEndpointBindingId" character varying(36), "endpointDefinitionId" character varying(36), "sourceServiceAssetId" character varying(36), "metricScope" "public"."runtime_metric_series_metricscope_enum" NOT NULL, "metricName" character varying(120) NOT NULL, "aggregationWindow" "public"."runtime_metric_series_aggregationwindow_enum" NOT NULL, "windowStartedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "windowEndedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "metricType" "public"."runtime_metric_series_metrictype_enum" NOT NULL DEFAULT 'counter', "value" double precision NOT NULL DEFAULT '0', "unit" character varying(32), "sampleCount" integer NOT NULL DEFAULT '1', "dimensions" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c956eceed1bd13efc5eff6d4fec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_898a4704bf170f0b4e7bee4ee8" ON "runtime_metric_series" ("metricScope", "windowStartedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_9b2140172938601a458984f864" ON "runtime_metric_series" ("metricName", "windowStartedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a1e48002f71ed0d77ef861ce8" ON "runtime_metric_series" ("runtimeAssetEndpointBindingId", "windowStartedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c59ed6275e5eaa43201959d4c5" ON "runtime_metric_series" ("runtimeAssetId", "windowStartedAt") `);
        await queryRunner.query(`CREATE TYPE "public"."runtime_observability_events_eventfamily_enum" AS ENUM('runtime.lifecycle', 'runtime.health', 'runtime.policy', 'runtime.publication', 'runtime.route', 'runtime.request', 'runtime.error', 'runtime.control')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_observability_events_severity_enum" AS ENUM('debug', 'info', 'warning', 'error', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_observability_events_status_enum" AS ENUM('success', 'failed', 'partial', 'active', 'offline', 'degraded')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_observability_events_actortype_enum" AS ENUM('system', 'user', 'runtime', 'scheduler')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_observability_events_retentionclass_enum" AS ENUM('short', 'standard', 'security', 'long')`);
        await queryRunner.query(`CREATE TABLE "runtime_observability_events" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "runtimeAssetId" character varying(36), "runtimeAssetEndpointBindingId" character varying(36), "endpointDefinitionId" character varying(36), "sourceServiceAssetId" character varying(36), "eventFamily" "public"."runtime_observability_events_eventfamily_enum" NOT NULL, "eventName" character varying(120) NOT NULL, "severity" "public"."runtime_observability_events_severity_enum" NOT NULL DEFAULT 'info', "status" "public"."runtime_observability_events_status_enum" NOT NULL DEFAULT 'success', "occurredAt" TIMESTAMP WITH TIME ZONE NOT NULL, "correlationId" character varying(120), "actorType" "public"."runtime_observability_events_actortype_enum" NOT NULL DEFAULT 'system', "actorId" character varying(36), "summary" character varying(500), "details" jsonb, "dimensions" jsonb, "retentionClass" "public"."runtime_observability_events_retentionclass_enum" NOT NULL DEFAULT 'standard', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6f8d430d6cba1da78277bf1bcf1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2eba4d2d1deb7439058411b5ba" ON "runtime_observability_events" ("correlationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_811dbf17e22bf3f4bc0f30e47b" ON "runtime_observability_events" ("status", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_cd73b7b0cf638d5b3113d9d131" ON "runtime_observability_events" ("severity", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5d2bb27857d9aaafbefa3c2852" ON "runtime_observability_events" ("eventFamily", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae4b736e4d2b58d32b5095b7ca" ON "runtime_observability_events" ("runtimeAssetEndpointBindingId", "occurredAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e1d57f7b6a4c739aa460fed3d" ON "runtime_observability_events" ("runtimeAssetId", "occurredAt") `);
        await queryRunner.query(`CREATE TYPE "public"."runtime_observability_states_scopetype_enum" AS ENUM('runtime_asset', 'runtime_membership', 'endpoint_definition', 'source_service_asset')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_observability_states_currentstatus_enum" AS ENUM('draft', 'active', 'degraded', 'offline')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_observability_states_healthstatus_enum" AS ENUM('unknown', 'healthy', 'degraded', 'unhealthy')`);
        await queryRunner.query(`CREATE TABLE "runtime_observability_states" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "scopeType" "public"."runtime_observability_states_scopetype_enum" NOT NULL, "runtimeAssetId" character varying(36), "runtimeAssetEndpointBindingId" character varying(36), "endpointDefinitionId" character varying(36), "sourceServiceAssetId" character varying(36), "currentStatus" "public"."runtime_observability_states_currentstatus_enum" NOT NULL DEFAULT 'draft', "healthStatus" "public"."runtime_observability_states_healthstatus_enum" NOT NULL DEFAULT 'unknown', "severity" character varying(16), "lastEventAt" TIMESTAMP WITH TIME ZONE, "lastSuccessAt" TIMESTAMP WITH TIME ZONE, "lastFailureAt" TIMESTAMP WITH TIME ZONE, "lastErrorCode" character varying(64), "lastErrorMessage" text, "summary" character varying(500), "counters" jsonb, "gauges" jsonb, "dimensions" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2b5d2c87ae60cfc31c002106b9b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_421c630442a8b8b7a7bc12d6e8" ON "runtime_observability_states" ("healthStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_b9b1ccce1eeb77c96ca75d4c48" ON "runtime_observability_states" ("currentStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_1ad7e7f3f31d107e86154c8530" ON "runtime_observability_states" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2635524c23c3528325712110f5" ON "runtime_observability_states" ("runtimeAssetId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_31dbfa87d727d5981ed35a515c" ON "runtime_observability_states" ("scopeType", "runtimeAssetId", "runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE TYPE "public"."ai_assistant_templates_type_enum" AS ENUM('claude_desktop', 'openai_assistant', 'anthropic_api', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."ai_assistant_templates_category_enum" AS ENUM('general', 'development', 'business', 'research', 'education')`);
        await queryRunner.query(`CREATE TYPE "public"."ai_assistant_templates_status_enum" AS ENUM('active', 'inactive', 'draft')`);
        await queryRunner.query(`CREATE TABLE "ai_assistant_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "type" "public"."ai_assistant_templates_type_enum" NOT NULL DEFAULT 'claude_desktop', "category" "public"."ai_assistant_templates_category_enum" NOT NULL DEFAULT 'general', "status" "public"."ai_assistant_templates_status_enum" NOT NULL DEFAULT 'active', "configTemplate" jsonb NOT NULL, "defaultValues" jsonb, "validationRules" jsonb, "tags" text, "isPublic" boolean NOT NULL DEFAULT true, "version" character varying NOT NULL DEFAULT '1.0.0', "author" character varying(100), "usageCount" integer NOT NULL DEFAULT '0', "rating" numeric(3,2) NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d2402915ed8d3b350b3c8b78561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_671f38118641e729c0b7669958" ON "ai_assistant_templates" ("status", "isPublic") `);
        await queryRunner.query(`CREATE INDEX "IDX_808d57a7a3e56bc043eba39545" ON "ai_assistant_templates" ("type", "category") `);
        await queryRunner.query(`CREATE TYPE "public"."ai_assistant_configs_status_enum" AS ENUM('generated', 'exported', 'applied', 'archived')`);
        await queryRunner.query(`CREATE TYPE "public"."ai_assistant_configs_exportformat_enum" AS ENUM('json', 'yaml', 'env', 'shell_script')`);
        await queryRunner.query(`CREATE TABLE "ai_assistant_configs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "templateId" uuid NOT NULL, "generatedConfig" jsonb NOT NULL, "customParameters" jsonb, "status" "public"."ai_assistant_configs_status_enum" NOT NULL DEFAULT 'generated', "exportFormat" "public"."ai_assistant_configs_exportformat_enum", "exportedContent" text, "tags" text, "isFavorite" boolean NOT NULL DEFAULT false, "usageCount" integer NOT NULL DEFAULT '0', "lastUsedAt" TIMESTAMP, "createdBy" character varying(100), "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_dcd11fc22ee1fb0e3fc9d103fb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05e34065f9197f0075ac77f780" ON "ai_assistant_configs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_0d12dfdffd091b709a66048207" ON "ai_assistant_configs" ("templateId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."source_service_instances_status_enum" AS ENUM('draft', 'healthy', 'unhealthy', 'offline')`);
        await queryRunner.query(`CREATE TABLE "source_service_instances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "sourceServiceAssetId" uuid NOT NULL, "name" character varying(255) NOT NULL, "environment" character varying(100) NOT NULL, "scheme" character varying(16) NOT NULL, "host" character varying(255) NOT NULL, "port" integer NOT NULL, "basePath" character varying(1024) NOT NULL DEFAULT '/', "enabled" boolean NOT NULL DEFAULT true, "status" "public"."source_service_instances_status_enum" NOT NULL DEFAULT 'draft', "priority" integer NOT NULL DEFAULT '100', "weight" integer NOT NULL DEFAULT '100', "isDefault" boolean NOT NULL DEFAULT false, "credentialRef" character varying(255), "tlsPolicyRef" character varying(255), "metadata" jsonb, "lastProbeStatus" character varying(32), "lastProbeAt" TIMESTAMP, "lastProbeLatencyMs" integer, "lastError" text, "archivedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c85214034df374dd7a7102bb94a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f390aaa00963aaf930b7f96f51" ON "source_service_instances" ("status", "enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_bd1964571f38932f02b96aebd8" ON "source_service_instances" ("sourceServiceAssetId", "environment", "enabled") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0f92e685581c791458b6c8af68" ON "source_service_instances" ("sourceServiceAssetId", "environment", "name") `);
        await queryRunner.query(`CREATE TABLE "endpoint_test_cases" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "endpointDefinitionId" character varying(36) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "enabled" boolean NOT NULL DEFAULT true, "requestTemplate" jsonb, "assertions" jsonb, "tags" jsonb, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_44c92c366fb386a47a107ce551c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2ee693e52d2c1e4d465d532815" ON "endpoint_test_cases" ("endpointDefinitionId", "enabled") `);
        await queryRunner.query(`CREATE TYPE "public"."endpoint_test_runs_status_enum" AS ENUM('success', 'failed')`);
        await queryRunner.query(`CREATE TABLE "endpoint_test_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "endpointDefinitionId" character varying(36) NOT NULL, "testCaseId" character varying(36), "sourceServiceInstanceId" character varying(36), "status" "public"."endpoint_test_runs_status_enum" NOT NULL, "requestHeaders" jsonb, "requestPayload" jsonb, "responseStatusCode" integer, "responseHeaders" jsonb, "responsePayload" jsonb, "durationMs" integer, "errorMessage" text, "metadata" jsonb, "executedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7558913e19f84ab25a250300323" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_33b89528103648b88c7c86bb82" ON "endpoint_test_runs" ("status", "executedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec7ed8579a9a2114ef1eb00a03" ON "endpoint_test_runs" ("testCaseId", "executedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c053461aadc401b6d584d493e3" ON "endpoint_test_runs" ("endpointDefinitionId", "executedAt") `);
        await queryRunner.query(`CREATE TYPE "public"."endpoint_test_samples_status_enum" AS ENUM('active', 'archived')`);
        await queryRunner.query(`CREATE TABLE "endpoint_test_samples" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "endpointDefinitionId" character varying(36) NOT NULL, "testCaseId" character varying(36), "testRunId" character varying(36) NOT NULL, "sourceServiceInstanceId" character varying(36), "fingerprint" character varying(64) NOT NULL, "title" character varying(255), "note" text, "enabled" boolean NOT NULL DEFAULT true, "status" "public"."endpoint_test_samples_status_enum" NOT NULL DEFAULT 'active', "requestHeaders" jsonb, "requestPayload" jsonb, "responseStatusCode" integer NOT NULL, "responseHeaders" jsonb, "responsePayload" jsonb, "durationMs" integer, "tags" jsonb, "metadata" jsonb, "capturedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "archivedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_50910f2541ace7a3842309573ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8f854a950227a717bf6f726c09" ON "endpoint_test_samples" ("status", "enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_729ae6099b4bb9144f2639f819" ON "endpoint_test_samples" ("fingerprint") `);
        await queryRunner.query(`CREATE INDEX "IDX_f1479053976c4686906b199cb3" ON "endpoint_test_samples" ("endpointDefinitionId", "capturedAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ab7fff83ce10709684bd168008" ON "endpoint_test_samples" ("testRunId") `);
        await queryRunner.query(`CREATE TYPE "public"."runtime_upstream_bindings_selectionmode_enum" AS ENUM('fixed_primary', 'healthy_priority')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_upstream_bindings_status_enum" AS ENUM('draft', 'verified', 'active', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "runtime_upstream_bindings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "runtimeAssetEndpointBindingId" character varying(36) NOT NULL, "sourceServiceAssetId" character varying(36) NOT NULL, "environment" character varying(100) NOT NULL, "selectionMode" "public"."runtime_upstream_bindings_selectionmode_enum" NOT NULL, "primaryInstanceId" character varying(36), "status" "public"."runtime_upstream_bindings_status_enum" NOT NULL DEFAULT 'draft', "revision" integer NOT NULL DEFAULT '1', "lastVerifiedAt" TIMESTAMP, "lastVerificationRunId" character varying(36), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_ba9afe6c99646ad9d4728e63a30" UNIQUE ("runtimeAssetEndpointBindingId"), CONSTRAINT "PK_e4699eba366455d08169f0b2afa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_96605e5f3fa22aebadcdc1ea44" ON "runtime_upstream_bindings" ("environment", "status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ba9afe6c99646ad9d4728e63a3" ON "runtime_upstream_bindings" ("runtimeAssetEndpointBindingId") `);
        await queryRunner.query(`CREATE TABLE "runtime_upstream_binding_instances" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "runtimeUpstreamBindingId" character varying(36) NOT NULL, "sourceServiceInstanceId" character varying(36) NOT NULL, "priority" integer NOT NULL DEFAULT '0', "orderIndex" integer NOT NULL DEFAULT '0', "weight" integer NOT NULL DEFAULT '1', "enabled" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_931b3c7dad618636a8e4860c4c4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_71d64ae3f496cedfc72e780331" ON "runtime_upstream_binding_instances" ("runtimeUpstreamBindingId", "enabled", "priority", "orderIndex") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d99880dc022aa1ee886688e887" ON "runtime_upstream_binding_instances" ("runtimeUpstreamBindingId", "sourceServiceInstanceId") `);
        await queryRunner.query(`CREATE TYPE "public"."runtime_verification_runs_trigger_enum" AS ENUM('deploy', 'redeploy', 'upstream_change', 'manual')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_verification_runs_status_enum" AS ENUM('planned', 'running', 'passed', 'failed', 'blocked')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_verification_runs_activationstatus_enum" AS ENUM('not_attempted', 'activated', 'retained_previous', 'blocked')`);
        await queryRunner.query(`CREATE TABLE "runtime_verification_runs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "runtimeAssetId" character varying(36) NOT NULL, "candidateRevision" character varying(64) NOT NULL, "previousActiveRevision" character varying(64), "trigger" "public"."runtime_verification_runs_trigger_enum" NOT NULL, "status" "public"."runtime_verification_runs_status_enum" NOT NULL, "activationStatus" "public"."runtime_verification_runs_activationstatus_enum" NOT NULL DEFAULT 'not_attempted', "totalCount" integer NOT NULL DEFAULT '0', "passedCount" integer NOT NULL DEFAULT '0', "failedCount" integer NOT NULL DEFAULT '0', "blockedCount" integer NOT NULL DEFAULT '0', "upstreamBindingRevisions" jsonb, "blockers" jsonb, "metadata" jsonb, "startedAt" TIMESTAMP WITH TIME ZONE, "completedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_20a9786bb67e18ac750bd1102f4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f1eb19f920ad31ee40dcfa4257" ON "runtime_verification_runs" ("candidateRevision") `);
        await queryRunner.query(`CREATE INDEX "IDX_d19d1e5ac1f2ef9f95ae43199c" ON "runtime_verification_runs" ("status", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_7621e2f741ca28bd3d948dca51" ON "runtime_verification_runs" ("runtimeAssetId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."runtime_verification_results_kind_enum" AS ENUM('smoke', 'regression', 'precondition', 'waiver')`);
        await queryRunner.query(`CREATE TYPE "public"."runtime_verification_results_status_enum" AS ENUM('pending', 'passed', 'failed', 'blocked', 'skipped')`);
        await queryRunner.query(`CREATE TABLE "runtime_verification_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "verificationRunId" character varying(36) NOT NULL, "runtimeMembershipId" character varying(36) NOT NULL, "endpointDefinitionId" character varying(36) NOT NULL, "endpointTestSampleId" character varying(36), "kind" "public"."runtime_verification_results_kind_enum" NOT NULL, "status" "public"."runtime_verification_results_status_enum" NOT NULL, "blockerCode" character varying(100), "errorMessage" text, "expectedStatusCode" integer, "actualStatusCode" integer, "durationMs" integer, "evidence" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_959cabf75381e3ec5a36c431536" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7c0770c6fc1c6bb2d49f19bc44" ON "runtime_verification_results" ("endpointTestSampleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e3f8f3f41a8bd665724bf9613d" ON "runtime_verification_results" ("verificationRunId", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b94c9d86a0f5adda3d796f3e1c" ON "runtime_verification_results" ("verificationRunId", "runtimeMembershipId") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("roleId" uuid NOT NULL, "permissionId" uuid NOT NULL, CONSTRAINT "PK_d430a02aad006d8a70f3acd7d03" PRIMARY KEY ("roleId", "permissionId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4599f8b8f548d35850afa2d12" ON "role_permissions" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_06792d0c62ce6b0203c03643cd" ON "role_permissions" ("permissionId") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("userId" uuid NOT NULL, "roleId" uuid NOT NULL, CONSTRAINT "PK_88481b0c4ed9ada47e9fdd67475" PRIMARY KEY ("userId", "roleId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_472b25323af01488f1f66a06b6" ON "user_roles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_86033897c009fcca8b6505d6be" ON "user_roles" ("roleId") `);
        await queryRunner.query(`ALTER TABLE "auth_configs" ADD CONSTRAINT "FK_c26de0f660ca6967931440c41e6" FOREIGN KEY ("serverId") REFERENCES "mcp_servers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "log_entries" ADD CONSTRAINT "FK_bd0b54acd354a14abe257494e82" FOREIGN KEY ("serverId") REFERENCES "mcp_servers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_logs" ADD CONSTRAINT "FK_af8bc5ddf6bb239c2b40173a78b" FOREIGN KEY ("serverId") REFERENCES "mcp_servers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_logs" ADD CONSTRAINT "FK_f4f5248b93c3ca62ed3761b30f1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "openapi_documents" ADD CONSTRAINT "FK_3a1c8bcd8eb7820826c7073421d" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ai_assistant_configs" ADD CONSTRAINT "FK_7fc97afe3f88aafbf18c408c0a2" FOREIGN KEY ("templateId") REFERENCES "ai_assistant_templates"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "source_service_instances" ADD CONSTRAINT "FK_48f531b0175e91696f5cd0100f9" FOREIGN KEY ("sourceServiceAssetId") REFERENCES "source_service_assets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_472b25323af01488f1f66a06b67" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_86033897c009fcca8b6505d6be2" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        if (queryRunner.connection.options.type !== 'postgres') return;
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_86033897c009fcca8b6505d6be2"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_472b25323af01488f1f66a06b67"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c"`);
        await queryRunner.query(`ALTER TABLE "source_service_instances" DROP CONSTRAINT "FK_48f531b0175e91696f5cd0100f9"`);
        await queryRunner.query(`ALTER TABLE "ai_assistant_configs" DROP CONSTRAINT "FK_7fc97afe3f88aafbf18c408c0a2"`);
        await queryRunner.query(`ALTER TABLE "openapi_documents" DROP CONSTRAINT "FK_3a1c8bcd8eb7820826c7073421d"`);
        await queryRunner.query(`ALTER TABLE "system_logs" DROP CONSTRAINT "FK_f4f5248b93c3ca62ed3761b30f1"`);
        await queryRunner.query(`ALTER TABLE "system_logs" DROP CONSTRAINT "FK_af8bc5ddf6bb239c2b40173a78b"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_cfa83f61e4d27a87fcae1e025ab"`);
        await queryRunner.query(`ALTER TABLE "log_entries" DROP CONSTRAINT "FK_bd0b54acd354a14abe257494e82"`);
        await queryRunner.query(`ALTER TABLE "auth_configs" DROP CONSTRAINT "FK_c26de0f660ca6967931440c41e6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86033897c009fcca8b6505d6be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_472b25323af01488f1f66a06b6"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06792d0c62ce6b0203c03643cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4599f8b8f548d35850afa2d12"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b94c9d86a0f5adda3d796f3e1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e3f8f3f41a8bd665724bf9613d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7c0770c6fc1c6bb2d49f19bc44"`);
        await queryRunner.query(`DROP TABLE "runtime_verification_results"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_verification_results_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_verification_results_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7621e2f741ca28bd3d948dca51"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d19d1e5ac1f2ef9f95ae43199c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1eb19f920ad31ee40dcfa4257"`);
        await queryRunner.query(`DROP TABLE "runtime_verification_runs"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_verification_runs_activationstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_verification_runs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_verification_runs_trigger_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d99880dc022aa1ee886688e887"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71d64ae3f496cedfc72e780331"`);
        await queryRunner.query(`DROP TABLE "runtime_upstream_binding_instances"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba9afe6c99646ad9d4728e63a3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96605e5f3fa22aebadcdc1ea44"`);
        await queryRunner.query(`DROP TABLE "runtime_upstream_bindings"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_upstream_bindings_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_upstream_bindings_selectionmode_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab7fff83ce10709684bd168008"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1479053976c4686906b199cb3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_729ae6099b4bb9144f2639f819"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f854a950227a717bf6f726c09"`);
        await queryRunner.query(`DROP TABLE "endpoint_test_samples"`);
        await queryRunner.query(`DROP TYPE "public"."endpoint_test_samples_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c053461aadc401b6d584d493e3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec7ed8579a9a2114ef1eb00a03"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33b89528103648b88c7c86bb82"`);
        await queryRunner.query(`DROP TABLE "endpoint_test_runs"`);
        await queryRunner.query(`DROP TYPE "public"."endpoint_test_runs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ee693e52d2c1e4d465d532815"`);
        await queryRunner.query(`DROP TABLE "endpoint_test_cases"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0f92e685581c791458b6c8af68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd1964571f38932f02b96aebd8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f390aaa00963aaf930b7f96f51"`);
        await queryRunner.query(`DROP TABLE "source_service_instances"`);
        await queryRunner.query(`DROP TYPE "public"."source_service_instances_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0d12dfdffd091b709a66048207"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05e34065f9197f0075ac77f780"`);
        await queryRunner.query(`DROP TABLE "ai_assistant_configs"`);
        await queryRunner.query(`DROP TYPE "public"."ai_assistant_configs_exportformat_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ai_assistant_configs_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_808d57a7a3e56bc043eba39545"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_671f38118641e729c0b7669958"`);
        await queryRunner.query(`DROP TABLE "ai_assistant_templates"`);
        await queryRunner.query(`DROP TYPE "public"."ai_assistant_templates_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ai_assistant_templates_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ai_assistant_templates_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31dbfa87d727d5981ed35a515c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2635524c23c3528325712110f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1ad7e7f3f31d107e86154c8530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9b1ccce1eeb77c96ca75d4c48"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_421c630442a8b8b7a7bc12d6e8"`);
        await queryRunner.query(`DROP TABLE "runtime_observability_states"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_observability_states_healthstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_observability_states_currentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_observability_states_scopetype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e1d57f7b6a4c739aa460fed3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae4b736e4d2b58d32b5095b7ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5d2bb27857d9aaafbefa3c2852"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd73b7b0cf638d5b3113d9d131"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_811dbf17e22bf3f4bc0f30e47b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2eba4d2d1deb7439058411b5ba"`);
        await queryRunner.query(`DROP TABLE "runtime_observability_events"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_observability_events_retentionclass_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_observability_events_actortype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_observability_events_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_observability_events_severity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_observability_events_eventfamily_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c59ed6275e5eaa43201959d4c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a1e48002f71ed0d77ef861ce8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9b2140172938601a458984f864"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_898a4704bf170f0b4e7bee4ee8"`);
        await queryRunner.query(`DROP TABLE "runtime_metric_series"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_metric_series_metrictype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_metric_series_aggregationwindow_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_metric_series_metricscope_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c442960f31c4b3043466f8da08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c54532f858d1c223d40a6d821f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1be17115c8ddd7233657265e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e8340ccffe02d565eed3a4364"`);
        await queryRunner.query(`DROP TABLE "gateway_consumer_credentials"`);
        await queryRunner.query(`DROP TYPE "public"."gateway_consumer_credentials_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3a4c2124d3a09a1830f500dab"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0a339d1242fc2d87f80f5b352c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72f0530d4cdcc947e2e33406d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f787ee33e930a71a010e53c654"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eaf52dad83edc21428b3fa1b32"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1abedaf643842a1ebeff5e93ac"`);
        await queryRunner.query(`DROP TABLE "gateway_access_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d7b04e03e153afceed995acc4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85c75b677c5c10bc99022797ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88d90bbe4eb5113863828bd2d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2b83bb98b3a6ecf8fcb01c724"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a61ea3be16d7b504d37ea68a41"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6e0221c655506d503484cf52e8"`);
        await queryRunner.query(`DROP TABLE "gateway_route_snapshots"`);
        await queryRunner.query(`DROP TABLE "gateway_route_bindings"`);
        await queryRunner.query(`DROP TYPE "public"."gateway_route_bindings_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."gateway_route_bindings_pathmatchmode_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bf37d3b26bafade0d4d6385bc4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a27af3b2b163918115580578f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a14db7f1483330b431c99b27e8"`);
        await queryRunner.query(`DROP TABLE "endpoint_publish_bindings"`);
        await queryRunner.query(`DROP TYPE "public"."endpoint_publish_bindings_publishstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."endpoint_publish_bindings_reviewstatus_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9021e17e279724424f99986fd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f8bbcb256a405eab0007a5a5b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_978a210f3599c1c7423182f779"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93c4ebca8d35af690a10753064"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e799fc3632f5bde1659207f6b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d1925c76e38c461873d8f078d"`);
        await queryRunner.query(`DROP TABLE "publication_audit_events"`);
        await queryRunner.query(`DROP TYPE "public"."publication_audit_events_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."publication_audit_events_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_229bf64062d89f697420effc81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e2e4a7e91c2e069847b69c2ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71184961a966965f2d1a07ab08"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d380c8ad525ed6964b0cd3872a"`);
        await queryRunner.query(`DROP TABLE "publication_batch_runs"`);
        await queryRunner.query(`DROP TYPE "public"."publication_batch_runs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."publication_batch_runs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53f90e5c9c8544c0a427c1dcfe"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b731eef4efcd5f4013ae908082"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6be2440698e2376a5f2e84c249"`);
        await queryRunner.query(`DROP TABLE "publication_profile_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_700ab179bf73420e265595a3a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48c1bcc4789a93a9b03d7f8a10"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3f1d3709f4e13fdd17fb4524be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f6f63d557a6caa1ff1bb69e464"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bcb384804888966597b29e249"`);
        await queryRunner.query(`DROP TABLE "publication_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."publication_profiles_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_efb699533b2cc4e467a6c428cf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e712a424ce528e5c8116ca50f"`);
        await queryRunner.query(`DROP TABLE "runtime_asset_endpoint_bindings"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_asset_endpoint_bindings_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a1892cfa29a4fdf4ee960c1a4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91af03862e2573dcde1f9dc54f"`);
        await queryRunner.query(`DROP TABLE "runtime_assets"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_assets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."runtime_assets_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ebe74ec16bc2db7f76a4c662bf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_795989a35d91fe69aedeaa01a3"`);
        await queryRunner.query(`DROP TABLE "endpoint_definitions"`);
        await queryRunner.query(`DROP TYPE "public"."endpoint_definitions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_003e5cc6b79472ad6baaa33162"`);
        await queryRunner.query(`DROP TABLE "source_service_assets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3a1c8bcd8eb7820826c7073421"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d6a5bfe2bd723f1dc5752bacf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_54a9714fc03cfc002e301b51f0"`);
        await queryRunner.query(`DROP TABLE "openapi_documents"`);
        await queryRunner.query(`DROP TYPE "public"."openapi_documents_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af8bc5ddf6bb239c2b40173a78"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aa05ada70e2c999cde45172c90"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4d57d243d15a45c981aaab0e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c6fb7db174ca4aa4d0033ab62b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8255879e189354927b5cd3186b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4f5248b93c3ca62ed3761b30f"`);
        await queryRunner.query(`DROP TABLE "system_logs"`);
        await queryRunner.query(`DROP TYPE "public"."system_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."system_logs_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."system_logs_eventtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4542dd2f38a61354a040ba9fd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_610102b60fea1455310ccd299d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_56b91d98f71e3d1b649ed6e9f3"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cfa83f61e4d27a87fcae1e025a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_76566a7a3b90863650d467bff6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2961862b2704794af56359ff0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ddc86298ac7fadad468b28d83"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48ce552495d14eae9b187bb671"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cf44c88049465f900899da21e"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."permissions_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c1544ddc5ab67b1c768ed74a5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e01fae4223e72fdd0bba2e6f6a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bd0b54acd354a14abe257494e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_88410904513ed6cfdd598a777b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_51bcf6d9189a9caa2956f7384d"`);
        await queryRunner.query(`DROP TABLE "log_entries"`);
        await queryRunner.query(`DROP TYPE "public"."log_entries_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."log_entries_level_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a9f26e310a0af26792c8762d3b"`);
        await queryRunner.query(`DROP TABLE "auth_configs"`);
        await queryRunner.query(`DROP TYPE "public"."auth_configs_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ee0138f3dd9575eedd37f2405"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ed02efd17d98567e515642eb0"`);
        await queryRunner.query(`DROP TABLE "mcp_servers"`);
        await queryRunner.query(`DROP TYPE "public"."mcp_servers_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."mcp_servers_transport_enum"`);
    }

}
