import { MigrationInterface, QueryRunner } from 'typeorm';
/** Independent production-format evidence storage; never promotes prototype rows. */
export class UpstreamProductionChallengeEvidencePostgres1790000011000 implements MigrationInterface {
 name = 'UpstreamProductionChallengeEvidencePostgres1790000011000';
 async up(runner: QueryRunner): Promise<void> {
  for (const sql of [
  "CREATE TABLE \"upstream_production_challenge_evidence\" (\"id\" uuid NOT NULL DEFAULT uuid_generate_v4(), \"evidenceKind\" character varying(32) NOT NULL DEFAULT 'production_challenge_v1', \"challengeVersion\" integer NOT NULL DEFAULT '1', \"sourceServiceAssetId\" character varying(36) NOT NULL, \"endpointDefinitionId\" character varying(36) NOT NULL, \"contextDigest\" character varying(64) NOT NULL, \"providerEpoch\" character varying(36) NOT NULL, \"runNonce\" character varying(36) NOT NULL, \"bindingRevision\" character varying(128) NOT NULL, \"bindingGeneration\" integer NOT NULL, \"actorId\" character varying(128) NOT NULL, \"result\" character varying(16) NOT NULL, \"failureCode\" character varying(64), \"anonymousBeforeStatus\" integer, \"wrongCredentialStatus\" integer, \"validCredentialStatus\" integer, \"anonymousAfterStatus\" integer, \"completedAt\" TIMESTAMP NOT NULL, \"expiresAt\" TIMESTAMP NOT NULL, \"revokedAt\" TIMESTAMP, \"createdAt\" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT \"CHK_upstream_production_passed\" CHECK (\"result\" <> 'passed' OR (\"anonymousBeforeStatus\" IS NOT NULL AND \"anonymousBeforeStatus\" IN (401, 403) AND \"wrongCredentialStatus\" IS NOT NULL AND \"wrongCredentialStatus\" IN (401, 403) AND \"validCredentialStatus\" IS NOT NULL AND \"validCredentialStatus\" BETWEEN 200 AND 299 AND \"anonymousAfterStatus\" IS NOT NULL AND \"anonymousAfterStatus\" IN (401, 403))), CONSTRAINT \"CHK_upstream_production_statuses\" CHECK ((\"anonymousBeforeStatus\" IS NULL OR \"anonymousBeforeStatus\" BETWEEN 100 AND 599) AND (\"wrongCredentialStatus\" IS NULL OR \"wrongCredentialStatus\" BETWEEN 100 AND 599) AND (\"validCredentialStatus\" IS NULL OR \"validCredentialStatus\" BETWEEN 100 AND 599) AND (\"anonymousAfterStatus\" IS NULL OR \"anonymousAfterStatus\" BETWEEN 100 AND 599)), CONSTRAINT \"CHK_upstream_production_generation\" CHECK (\"bindingGeneration\" >= 1), CONSTRAINT \"CHK_upstream_production_failure\" CHECK (\"failureCode\" IS NULL OR \"failureCode\" IN ('BINDING_UNAVAILABLE', 'CONTEXT_CHANGED', 'CHALLENGE_STATUS_REJECTED', 'CHALLENGE_TRANSPORT_FAILED', 'CHALLENGE_CANCELLED', 'CHALLENGE_TIMEOUT')), CONSTRAINT \"CHK_upstream_production_revoked\" CHECK (\"revokedAt\" IS NULL OR \"revokedAt\" >= \"completedAt\"), CONSTRAINT \"CHK_upstream_production_expiry\" CHECK (\"expiresAt\" > \"completedAt\"), CONSTRAINT \"CHK_upstream_production_result\" CHECK (\"result\" IN ('passed', 'failed')), CONSTRAINT \"CHK_upstream_production_version\" CHECK (\"challengeVersion\" = 1), CONSTRAINT \"CHK_upstream_production_kind\" CHECK (\"evidenceKind\" = 'production_challenge_v1'), CONSTRAINT \"PK_6345ece73a48c838410da0ad3f7\" PRIMARY KEY (\"id\"))",
  "CREATE INDEX \"IDX_upstream_production_endpoint_created\" ON \"upstream_production_challenge_evidence\" (\"endpointDefinitionId\", \"createdAt\") "
]) await runner.query(sql);
 }
 async down(runner: QueryRunner): Promise<void> { await runner.query('DROP TABLE "upstream_production_challenge_evidence"'); }
}
