import { MigrationInterface, QueryRunner } from 'typeorm';
/** Independent production-format evidence storage; never promotes prototype rows. */
export class UpstreamProductionChallengeEvidenceSqlite1790000010000 implements MigrationInterface {
 name = 'UpstreamProductionChallengeEvidenceSqlite1790000010000';
 async up(runner: QueryRunner): Promise<void> {
  for (const sql of [
  "CREATE TABLE \"upstream_production_challenge_evidence\" (\"id\" varchar PRIMARY KEY NOT NULL, \"evidenceKind\" varchar(32) NOT NULL DEFAULT ('production_challenge_v1'), \"challengeVersion\" integer NOT NULL DEFAULT (1), \"sourceServiceAssetId\" varchar(36) NOT NULL, \"endpointDefinitionId\" varchar(36) NOT NULL, \"contextDigest\" varchar(64) NOT NULL, \"providerEpoch\" varchar(36) NOT NULL, \"runNonce\" varchar(36) NOT NULL, \"bindingRevision\" varchar(128) NOT NULL, \"bindingGeneration\" integer NOT NULL, \"actorId\" varchar(128) NOT NULL, \"result\" varchar(16) NOT NULL, \"failureCode\" varchar(64), \"anonymousBeforeStatus\" integer, \"wrongCredentialStatus\" integer, \"validCredentialStatus\" integer, \"anonymousAfterStatus\" integer, \"completedAt\" datetime NOT NULL, \"expiresAt\" datetime NOT NULL, \"revokedAt\" datetime, \"createdAt\" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT \"CHK_upstream_production_passed\" CHECK (\"result\" <> 'passed' OR (\"anonymousBeforeStatus\" IS NOT NULL AND \"anonymousBeforeStatus\" IN (401, 403) AND \"wrongCredentialStatus\" IS NOT NULL AND \"wrongCredentialStatus\" IN (401, 403) AND \"validCredentialStatus\" IS NOT NULL AND \"validCredentialStatus\" BETWEEN 200 AND 299 AND \"anonymousAfterStatus\" IS NOT NULL AND \"anonymousAfterStatus\" IN (401, 403))), CONSTRAINT \"CHK_upstream_production_statuses\" CHECK ((\"anonymousBeforeStatus\" IS NULL OR \"anonymousBeforeStatus\" BETWEEN 100 AND 599) AND (\"wrongCredentialStatus\" IS NULL OR \"wrongCredentialStatus\" BETWEEN 100 AND 599) AND (\"validCredentialStatus\" IS NULL OR \"validCredentialStatus\" BETWEEN 100 AND 599) AND (\"anonymousAfterStatus\" IS NULL OR \"anonymousAfterStatus\" BETWEEN 100 AND 599)), CONSTRAINT \"CHK_upstream_production_generation\" CHECK (\"bindingGeneration\" >= 1), CONSTRAINT \"CHK_upstream_production_failure\" CHECK (\"failureCode\" IS NULL OR \"failureCode\" IN ('BINDING_UNAVAILABLE', 'CONTEXT_CHANGED', 'CHALLENGE_STATUS_REJECTED', 'CHALLENGE_TRANSPORT_FAILED', 'CHALLENGE_CANCELLED', 'CHALLENGE_TIMEOUT')), CONSTRAINT \"CHK_upstream_production_revoked\" CHECK (\"revokedAt\" IS NULL OR \"revokedAt\" >= \"completedAt\"), CONSTRAINT \"CHK_upstream_production_expiry\" CHECK (\"expiresAt\" > \"completedAt\"), CONSTRAINT \"CHK_upstream_production_result\" CHECK (\"result\" IN ('passed', 'failed')), CONSTRAINT \"CHK_upstream_production_version\" CHECK (\"challengeVersion\" = 1), CONSTRAINT \"CHK_upstream_production_kind\" CHECK (\"evidenceKind\" = 'production_challenge_v1'))",
  "CREATE INDEX \"IDX_upstream_production_endpoint_created\" ON \"upstream_production_challenge_evidence\" (\"endpointDefinitionId\", \"createdAt\") "
]) await runner.query(sql);
 }
 async down(runner: QueryRunner): Promise<void> { await runner.query('DROP TABLE "upstream_production_challenge_evidence"'); }
}
